<a href="https://colab.research.google.com/github/vaishnaviPatil1111/Python/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Exploration Questions:**

In [1]:
import numpy as np
import pandas as pd

## ***Questions on Sales Data for Pandas:***

In [ ]:
import numpy as np
import pandas as pd

In [2]:
#1.	Load the sales data CSV file into a Pandas DataFrame.
df = pd.read_csv("/content/drive/MyDrive/Data Sets/sales_data.csv")
df

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
8,1009,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
10,1011,Employee_11,46,Electronics,West,26253,49772,No,7,28090.71
11,1012,Employee_12,43,Clothing,North,32197,47360,No,6,34128.82
12,1013,Employee_13,41,Clothing,West,5955,28323,No,6,6312.30
13,1014,Employee_14,50,Electronics,West,30025,34692,No,9,32727.25
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31
15,1016,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
17,1018,Employee_18,31,Home Decor,East,30349,24158,Yes,5,31866.45
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
24,1025,Employee_25,55,Clothing,North,17986,28587,No,7,19245.02
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
27,1028,Employee_28,33,Electronics,West,33593,23312,Yes,5,35272.65
28,1029,Employee_29,44,Clothing,West,7157,10232,No,9,7801.13
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
30,1031,Employee_31,40,Home Decor,West,38718,25399,Yes,7,41428.26
31,1032,Employee_32,54,Clothing,North,34702,47611,No,3,35743.06
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
36,1037,Employee_37,26,Clothing,West,25221,20484,Yes,9,27490.89
37,1038,Employee_38,49,Electronics,North,25613,28763,No,10,28174.30
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
41,1042,Employee_42,37,Home Decor,South,28905,32080,No,9,31506.45
42,1043,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#2.	Display the first 5 rows of the DataFrame.
df.head(5)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08

In [ ]:
#3.	Show the last 5 rows of the DataFrame.
df.tail(5)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#4.	Get the shape (number of rows and columns) of the dataset.
df.shape

(50, 10)

In [ ]:
#5.	Display summary statistics of all numerical columns.
# avg, max, min, std, 1st 2nd 3rd quarter value, count, sum

df.describe()

,EmployeeID,Age,SalesAmount,Target,CommissionPercentage,TotalEarnings
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,1025.50000,39.780000,29381.580000,29492.040000,5.860000,31034.621800
std,14.57738,10.525557,12096.724585,13022.222386,2.432853,12703.757127
min,1001.00000,22.000000,5377.000000,10151.000000,2.000000,5538.310000
25%,1013.25000,31.000000,20736.500000,17249.500000,4.000000,22142.187500
50%,1025.50000,41.000000,29747.000000,28675.000000,6.000000,31686.450000
75%,1037.75000,49.000000,38276.750000,41410.500000,8.000000,40749.962500
max,1050.00000,55.000000,49578.000000,49772.000000,10.000000,52860.600000

In [ ]:
#6.	Get column names of the dataset.
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Department', 'Region', 'SalesAmount',
       'Target', 'TargetAchieved', 'CommissionPercentage', 'TotalEarnings'],
      dtype='object')

In [ ]:
#7.	Check for missing values in the dataset.
df.isnull().sum()

EmployeeID              0
Name                    0
Age                     0
Department              0
Region                  0
SalesAmount             0
Target                  0
TargetAchieved          0
CommissionPercentage    0
TotalEarnings           0
dtype: int64

In [ ]:
#8.	Get the data types of each column.
df.dtypes

EmployeeID                int64
Name                     object
Age                       int64
Department               object
Region                   object
SalesAmount               int64
Target                    int64
TargetAchieved           object
CommissionPercentage      int64
TotalEarnings           float64
dtype: object

In [ ]:
#9.	Sort the dataset by SalesAmount in descending order.
df.sort_values(by='SalesAmount',ascending=False)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
8,1009,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
15,1016,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
42,1043,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
30,1031,Employee_31,40,Home Decor,West,38718,25399,Yes,7,41428.26
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
31,1032,Employee_32,54,Clothing,North,34702,47611,No,3,35743.06
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
27,1028,Employee_28,33,Electronics,West,33593,23312,Yes,5,35272.65
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
11,1012,Employee_12,43,Clothing,North,32197,47360,No,6,34128.82
17,1018,Employee_18,31,Home Decor,East,30349,24158,Yes,5,31866.45
13,1014,Employee_14,50,Electronics,West,30025,34692,No,9,32727.25
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
41,1042,Employee_42,37,Home Decor,South,28905,32080,No,9,31506.45
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
10,1011,Employee_11,46,Electronics,West,26253,49772,No,7,28090.71
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
37,1038,Employee_38,49,Electronics,North,25613,28763,No,10,28174.30
36,1037,Employee_37,26,Clothing,West,25221,20484,Yes,9,27490.89
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
24,1025,Employee_25,55,Clothing,North,17986,28587,No,7,19245.02
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
28,1029,Employee_29,44,Clothing,West,7157,10232,No,9,7801.13
12,1013,Employee_13,41,Clothing,West,5955,28323,No,6,6312.30
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31

In [ ]:
#10.	Select only EmployeeID, Name, and SalesAmount columns.
df[['EmployeeID', 'Name', 'SalesAmount']]

    EmployeeID         Name  SalesAmount
0         1001   Employee_1        34200
1         1002   Employee_2        32850
2         1003   Employee_3        43267
3         1004   Employee_4        17263
4         1005   Employee_5        37427
5         1006   Employee_6        25853
6         1007   Employee_7         7695
7         1008   Employee_8        47690
8         1009   Employee_9        49578
9         1010  Employee_10        18766
10        1011  Employee_11        26253
11        1012  Employee_12        32197
12        1013  Employee_13         5955
13        1014  Employee_14        30025
14        1015  Employee_15         5377
15        1016  Employee_16        48945
16        1017  Employee_17        40326
17        1018  Employee_18        30349
18        1019  Employee_19        12766
19        1020  Employee_20        28150
20        1021  Employee_21        27366
21        1022  Employee_22         8939
22        1023  Employee_23        41728
23        1024  Employee_24        36688
24        1025  Employee_25        17986
25        1026  Employee_26        21533
26        1027  Employee_27        38560
27        1028  Employee_28        33593
28        1029  Employee_29         7157
29        1030  Employee_30        27787
30        1031  Employee_31        38718
31        1032  Employee_32        34702
32        1033  Employee_33        29469
33        1034  Employee_34        49111
34        1035  Employee_35        39717
35        1036  Employee_36        20471
36        1037  Employee_37        25221
37        1038  Employee_38        25613
38        1039  Employee_39        35710
39        1040  Employee_40        27167
40        1041  Employee_41        44983
41        1042  Employee_42        28905
42        1043  Employee_43        46558
43        1044  Employee_44        11767
44        1045  Employee_45        40454
45        1046  Employee_46        32685
46        1047  Employee_47        37045
47        1048  Employee_48        18960
48        1049  Employee_49        17997
49        1050  Employee_50        27557

In [ ]:
#*Filtering & Conditional Selection ( SQL limit , Sort asc desc , Where )*
#11.	Find all employees who achieved their sales target.
df.head()
df['TargetAchieved']=='yes'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: TargetAchieved, dtype: bool

In [ ]:
#12.	Find employees who belong to the "Electronics" department.
df['Department']=='Electronics'

0      True
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13     True
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28    False
29    False
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44     True
45    False
46    False
47    False
48    False
49    False
Name: Department, dtype: bool

In [ ]:
#13.	Find employees who belong to the "West" region and achieved their target.
df['Region']=='West'

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
12     True
13     True
14    False
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28     True
29     True
30     True
31    False
32    False
33    False
34    False
35     True
36     True
37    False
38     True
39     True
40    False
41    False
42     True
43     True
44    False
45    False
46    False
47    False
48    False
49    False
Name: Region, dtype: bool

In [ ]:
#14.	Filter employees who have a SalesAmount greater than 30,000.
df['SalesAmount']>30000

0      True
1      True
2      True
3     False
4      True
5     False
6     False
7      True
8      True
9     False
10    False
11     True
12    False
13     True
14    False
15     True
16     True
17     True
18    False
19    False
20    False
21    False
22     True
23     True
24    False
25    False
26     True
27     True
28    False
29    False
30     True
31     True
32    False
33     True
34     True
35    False
36    False
37    False
38     True
39    False
40     True
41    False
42     True
43    False
44     True
45     True
46     True
47    False
48    False
49    False
Name: SalesAmount, dtype: bool

In [ ]:
#15.	Find employees who have a commission percentage greater than 5%.
df.head()
df['CommissionPercentage'] > 5

0     False
1      True
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9     False
10     True
11     True
12     True
13     True
14    False
15     True
16     True
17    False
18     True
19    False
20    False
21     True
22     True
23    False
24     True
25     True
26     True
27    False
28     True
29     True
30     True
31    False
32    False
33     True
34    False
35     True
36     True
37     True
38     True
39    False
40    False
41     True
42     True
43     True
44    False
45    False
46     True
47     True
48    False
49    False
Name: CommissionPercentage, dtype: bool

In [ ]:
#16.	Find employees who did not achieve their target.
df['TargetAchieved'] == 'No'

0     False
1      True
2     False
3      True
4     False
5      True
6      True
7      True
8     False
9     False
10     True
11     True
12     True
13     True
14     True
15    False
16     True
17    False
18     True
19    False
20    False
21     True
22    False
23    False
24     True
25     True
26     True
27    False
28     True
29     True
30    False
31     True
32    False
33    False
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41     True
42    False
43     True
44    False
45     True
46    False
47    False
48    False
49    False
Name: TargetAchieved, dtype: bool

In [ ]:
#17.	Find employees who belong to either "Groceries" or "Automobile" department.
df[(df['Department'] == 'Groceries') | (df['Department'] == 'Automobile')]

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#18.	Find employees with TotalEarnings greater than 40,000.
df['TotalEarnings'] > 40000

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30     True
31    False
32    False
33     True
34     True
35    False
36    False
37    False
38    False
39    False
40     True
41    False
42     True
43    False
44     True
45    False
46     True
47    False
48    False
49    False
Name: TotalEarnings, dtype: bool

In [ ]:
#19.	Find employees who are older than 40 years and achieved their target.
df.head()
df[(df['Age'] > 40) & (df['TargetAchieved'] == 'Yes')]

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85

In [ ]:
#20.	Select employees whose names contain "10".
df['Name'].str.contains('10')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Name, dtype: bool

In [4]:
#Aggregation & Grouping (Pivot , Group by )
#21.	Find the average sales amount per department.
df.groupby('Department')['SalesAmount'].mean()

Department
Automobile     26610.818182
Clothing       26593.181818
Electronics    32422.300000
Groceries      27139.000000
Home Decor     36027.750000
Name: SalesAmount, dtype: float64

In [7]:
#22.	Count the number of employees in each region.
df.groupby('Region')['EmployeeID'].count()

Region
East     16
North    12
South     6
West     16
Name: EmployeeID, dtype: int64

In [9]:
#23.	Find the highest SalesAmount in each department.
df.head()
df.groupby('Department')['SalesAmount'].max()

Department
Automobile     44983
Clothing       39717
Electronics    49111
Groceries      47690
Home Decor     49578
Name: SalesAmount, dtype: int64

In [10]:
#24.	Find the lowest SalesAmount in each department.
df.groupby('Department')['SalesAmount'].min()

Department
Automobile      7695
Clothing        5955
Electronics    17263
Groceries       5377
Home Decor     17997
Name: SalesAmount, dtype: int64

In [12]:
#25.	Find the employee with the highest total earnings.
df.head()
df.groupby('TotalEarnings')['EmployeeID'].max()

TotalEarnings
5538.31     1015
6312.30     1013
7801.13     1029
8464.50     1007
9654.12     1022
12590.69    1044
13914.94    1019
17780.89    1004
18896.85    1049
19245.02    1025
19516.64    1010
20476.80    1048
21699.26    1036
23470.97    1026
26887.12    1006
27490.89    1037
27982.01    1040
28090.71    1011
28174.30    1038
28734.30    1021
28934.85    1050
29276.00    1020
29454.22    1030
30058.38    1033
31506.45    1042
31866.45    1018
32727.25    1014
33338.70    1046
34128.82    1012
35272.65    1028
35743.06    1032
35806.50    1002
35910.00    1001
37788.64    1024
37852.60    1039
38924.08    1005
40379.05    1047
40873.60    1027
40908.51    1035
41263.08    1045
41428.26    1031
42745.56    1017
44132.34    1003
45483.52    1023
46332.49    1041
49120.70    1008
50282.64    1043
52057.66    1034
52552.68    1009
52860.60    1016
Name: EmployeeID, dtype: int64

In [14]:
#26.	Count the number of employees who achieved and did not achieve their target.
df.head()
df.groupby('TargetAchieved')['EmployeeID'].count()

TargetAchieved
No     24
Yes    26
Name: EmployeeID, dtype: int64

In [16]:
#27.	Find the average commission percentage per department.
df.groupby('Department')['CommissionPercentage'].mean()

Department
Automobile     5.818182
Clothing       5.909091
Electronics    5.900000
Groceries      5.400000
Home Decor     6.375000
Name: CommissionPercentage, dtype: float64

In [18]:
#28.	Find the highest TotalEarnings per region.
df.head()
df.groupby('Region')['TotalEarnings'].max()

Region
East     52860.60
North    40908.51
South    49120.70
West     50282.64
Name: TotalEarnings, dtype: float64

In [19]:
#29.	Find the lowest TotalEarnings per department.
df.groupby('Region')['TotalEarnings'].min()

Region
East      9654.12
North    13914.94
South     5538.31
West      6312.30
Name: TotalEarnings, dtype: float64

In [20]:
#30.	Count the number of employees per department
df.groupby('Department')['EmployeeID'].count()

Department
Automobile     11
Clothing       11
Electronics    10
Groceries      10
Home Decor      8
Name: EmployeeID, dtype: int64

## ***Questions on Cars Data for Pandas:***

In [21]:
import numpy as np
import pandas as pd

In [22]:
df1 = pd.read_csv("/content/drive/MyDrive/Data Sets/cars_data (1).csv")
df1

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
0,1,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941
1,2,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006
2,3,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970
3,4,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880
4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077
5,6,Ford,Explorer,2011,77712,Diesel,41.56,405,341,4,Manual,No,North,2,68106
6,7,Honda,Pilot,2013,10300,Diesel,17.70,275,332,4,Manual,Yes,South,4,7139
7,8,Toyota,Prius,2012,17388,Petrol,45.71,378,156,5,Manual,No,South,5,10033
8,9,Mercedes,GLE,2013,25585,Electric,24.16,326,309,4,Automatic,No,South,1,18884
9,10,Ford,Explorer,2012,37985,Diesel,37.34,239,473,4,Automatic,No,West,2,32984
10,11,Ford,Fiesta,2019,67254,Petrol,15.29,134,480,7,Automatic,Yes,South,3,52939
11,12,Honda,Civic,2020,64608,Electric,10.61,564,332,5,Manual,No,North,5,45789
12,13,Mercedes,E-Class,2012,29315,Electric,26.83,352,206,7,Manual,Yes,East,1,14665
13,14,Honda,CR-V,2022,30202,Petrol,39.59,475,312,2,Manual,No,East,1,16262
14,15,Honda,Civic,2015,34824,Electric,37.11,377,289,4,Manual,Yes,West,3,21668
15,16,Ford,Focus,2019,43068,Electric,19.92,249,389,5,Manual,Yes,West,3,27690
16,17,Toyota,Highlander,2020,71536,Petrol,37.93,493,458,7,Manual,No,South,2,50319
17,18,Ford,Fiesta,2020,63321,Diesel,24.16,407,489,4,Automatic,No,North,1,46879
18,19,Mercedes,GLC,2013,50248,Diesel,46.46,230,658,2,Manual,No,East,4,27816
19,20,Honda,Civic,2017,37778,Petrol,24.12,563,163,2,Manual,No,South,2,32158
20,21,Honda,CR-V,2014,46256,Petrol,16.72,266,255,2,Manual,Yes,East,3,32004
21,22,Mercedes,GLC,2017,66352,Petrol,43.12,156,516,7,Manual,Yes,East,5,52467
22,23,Mercedes,C-Class,2021,35241,Electric,33.54,538,342,2,Manual,Yes,East,2,22622
23,24,Toyota,Camry,2013,28883,Petrol,38.70,213,233,2,Automatic,Yes,South,5,19527
24,25,Ford,Mustang,2011,62600,Diesel,48.76,496,439,4,Automatic,No,West,4,45733
25,26,BMW,X3,2010,24263,Electric,13.32,200,415,2,Automatic,Yes,South,5,15836
26,27,Mercedes,S-Class,2013,27977,Petrol,46.51,300,160,5,Automatic,Yes,West,4,17662
27,28,Toyota,Corolla,2010,62300,Petrol,34.26,145,454,4,Manual,No,East,3,37752
28,29,Ford,F-150,2020,30749,Electric,14.78,556,155,2,Manual,No,South,2,19501
29,30,Toyota,RAV4,2015,36720,Diesel,40.73,147,484,2,Automatic,No,North,1,24917
30,31,Honda,Fit,2015,38883,Diesel,46.20,565,150,7,Manual,No,West,3,31463
31,32,Mercedes,C-Class,2012,25800,Petrol,45.72,359,291,5,Automatic,No,South,3,18886
32,33,Ford,Fiesta,2018,56907,Electric,30.46,506,322,4,Manual,Yes,West,1,49844
33,34,Mercedes,GLE,2023,75933,Diesel,12.74,244,399,4,Manual,Yes,East,5,63652
34,35,Ford,Fiesta,2021,77675,Diesel,38.46,118,496,5,Automatic,No,North,4,66231
35,36,BMW,3 Series,2010,54825,Diesel,20.94,579,491,5,Automatic,No,West,1,40647
36,37,BMW,X3,2013,29725,Petrol,44.13,235,312,7,Automatic,Yes,South,1,18958
37,38,Toyota,Prius,2018,64805,Electric,31.16,231,210,5,Automatic,No,South,3,40083
38,39,Toyota,Camry,2016,20997,Petrol,31.47,107,688,5,Manual,Yes,South,1,14372
39,40,Toyota,RAV4,2022,68178,Petrol,25.01,134,612,7,Manual,No,West,1,43926
40,41,Honda,Pilot,2018,76039,Diesel,27.92,498,509,7,Manual,No,North,2,59039
41,42,Ford,Focus,2020,16659,Petrol,26.08,508,496,4,Manual,No,East,5,14128
42,43,Honda,Fit,2014,39685,Diesel,49.65,195,266,2,Automatic,Yes,South,2,27197
43,44,BMW,X5,2023,60310,Petrol,14.98,215,375,2,Automatic,Yes,North,3,53420
44,45,Mercedes,S-Class,2012,69705,Petrol,16.50,422,586,4,Automatic,Yes,West,5,50597
45,46,Ford,Explorer,2016,17051,Electric,38.91,558,193,5,Manual,No,West,1,11446
46,47,Honda,Accord,2015,49903,Diesel,37.78,243,472,5,Automatic,No,North,5,33468
47,48,Toyota,Highlander,2016,25138,Petrol,49.10,280,202,4,Automatic,No,West,2,22109
48,49,Toyota,Camry,2014,39294,Petrol,36.95,506,362,5,Manual,Yes,North,1,20293
49,50,BMW,5 Series,2014,28773,Diesel,44.83,248,252,2,Manual,Yes,South,1,25545

In [ ]:
# 1.	Display the first 5 rows of the dataset.
df1.head(5)

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
0,1,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941
1,2,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006
2,3,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970
3,4,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880
4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077

In [ ]:
# 2.	Show the last 5 rows of the dataset.
df1.tail(5)

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
45,46,Ford,Explorer,2016,17051,Electric,38.91,558,193,5,Manual,No,West,1,11446
46,47,Honda,Accord,2015,49903,Diesel,37.78,243,472,5,Automatic,No,North,5,33468
47,48,Toyota,Highlander,2016,25138,Petrol,49.10,280,202,4,Automatic,No,West,2,22109
48,49,Toyota,Camry,2014,39294,Petrol,36.95,506,362,5,Manual,Yes,North,1,20293
49,50,BMW,5 Series,2014,28773,Diesel,44.83,248,252,2,Manual,Yes,South,1,25545

In [ ]:
# 3.	Get the shape (number of rows and columns) of the dataset.
df1.shape

(50, 15)

In [ ]:
# 4.	Display summary statistics for all numerical columns.
df1.describe()

,CarID,Year,Price,Mileage,Horsepower,Torque,Seats,SafetyRating,ResaleValue
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,25.50000,2015.880000,45147.320000,32.278200,324.760000,361.700000,4.220000,2.720000,33150.600000
std,14.57738,3.847289,19667.845968,11.848107,151.517974,139.352914,1.729575,1.512398,16788.502376
min,1.00000,2010.000000,10300.000000,10.610000,107.000000,150.000000,2.000000,1.000000,7139.000000
25%,13.25000,2013.000000,28991.000000,21.915000,213.500000,257.750000,2.000000,1.000000,19129.750000
50%,25.50000,2015.000000,39489.500000,35.605000,277.500000,336.500000,4.000000,2.500000,29393.000000
75%,37.75000,2019.750000,63140.750000,42.237500,488.500000,478.250000,5.000000,4.000000,46606.500000
max,50.00000,2023.000000,79402.000000,49.650000,579.000000,688.000000,7.000000,5.000000,68941.000000

In [ ]:
# 5.	Get the column names of the dataset.
df1.columns

Index(['CarID', 'Brand', 'Model', 'Year', 'Price', 'FuelType', 'Mileage',
       'Horsepower', 'Torque', 'Seats', 'Transmission', 'Sold', 'Region',
       'SafetyRating', 'ResaleValue'],
      dtype='object')

In [ ]:
# 6.	Check for missing values in the dataset.
df1.isnull().sum()

CarID           0
Brand           0
Model           0
Year            0
Price           0
FuelType        0
Mileage         0
Horsepower      0
Torque          0
Seats           0
Transmission    0
Sold            0
Region          0
SafetyRating    0
ResaleValue     0
dtype: int64

In [ ]:
# 7.	Get the data types of each column Filtering and Sorting Questions
df1.dtypes

CarID             int64
Brand            object
Model            object
Year              int64
Price             int64
FuelType         object
Mileage         float64
Horsepower        int64
Torque            int64
Seats             int64
Transmission     object
Sold             object
Region           object
SafetyRating      int64
ResaleValue       int64
dtype: object

In [ ]:
# 8.	Sort the dataset by Price in descending order.
df1[['Price']].sort_values(by='Price',ascending=False)

    Price
0   79402
5   77712
34  77675
40  76039
33  75933
16  71536
44  69705
39  68178
10  67254
21  66352
37  64805
11  64608
17  63321
24  62600
27  62300
43  60310
4   59752
32  56907
35  54825
18  50248
46  49903
20  46256
15  43068
2   40886
42  39685
48  39294
30  38883
9   37985
19  37778
29  36720
22  35241
14  34824
3   34459
28  30749
13  30202
36  29725
12  29315
23  28883
49  28773
26  27977
31  25800
8   25585
47  25138
25  24263
1   24117
38  20997
7   17388
45  17051
41  16659
6   10300

In [ ]:
# 9.	Select only the Brand, Model, and Price columns.
df1[['Brand','Model','Price']]

       Brand       Model  Price
0        BMW    5 Series  79402
1   Mercedes     E-Class  24117
2   Mercedes         GLC  40886
3      Honda        CR-V  34459
4   Mercedes     C-Class  59752
5       Ford    Explorer  77712
6      Honda       Pilot  10300
7     Toyota       Prius  17388
8   Mercedes         GLE  25585
9       Ford    Explorer  37985
10      Ford      Fiesta  67254
11     Honda       Civic  64608
12  Mercedes     E-Class  29315
13     Honda        CR-V  30202
14     Honda       Civic  34824
15      Ford       Focus  43068
16    Toyota  Highlander  71536
17      Ford      Fiesta  63321
18  Mercedes         GLC  50248
19     Honda       Civic  37778
20     Honda        CR-V  46256
21  Mercedes         GLC  66352
22  Mercedes     C-Class  35241
23    Toyota       Camry  28883
24      Ford     Mustang  62600
25       BMW          X3  24263
26  Mercedes     S-Class  27977
27    Toyota     Corolla  62300
28      Ford       F-150  30749
29    Toyota        RAV4  36720
30     Honda         Fit  38883
31  Mercedes     C-Class  25800
32      Ford      Fiesta  56907
33  Mercedes         GLE  75933
34      Ford      Fiesta  77675
35       BMW    3 Series  54825
36       BMW          X3  29725
37    Toyota       Prius  64805
38    Toyota       Camry  20997
39    Toyota        RAV4  68178
40     Honda       Pilot  76039
41      Ford       Focus  16659
42     Honda         Fit  39685
43       BMW          X5  60310
44  Mercedes     S-Class  69705
45      Ford    Explorer  17051
46     Honda      Accord  49903
47    Toyota  Highlander  25138
48    Toyota       Camry  39294
49       BMW    5 Series  28773

## ***Questions on Airline Dataset:***

In [ ]:
# 1.	Load the CSV file into a Pandas DataFrame.
df2 = pd .read_csv("/content/drive/MyDrive/Data Sets/airline_passengers_indian.csv")
df2

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold
5,6,Aryan,Nair,22,Male,LH606,Hyderabad,Munich,850,Economy,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
8,9,Saanvi,Joshi,29,Female,UA909,Lucknow,San Francisco,700,Economy,On Hold
9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed
10,11,Advait,Kapoor,32,Male,BA211,Mumbai,London,720,Business,Confirmed
11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
13,14,Kiaan,Jain,31,Male,QR544,Chennai,Dubai,890,Business,On Hold
14,15,Tanish,Agarwal,35,Male,LH633,Kolkata,Tokyo,800,Economy,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [ ]:
#2.	Display the first 5 rows of the DataFrame.
df2.head(5)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold

In [ ]:
#3.	Display the last 5 rows of the DataFrame.
df2.tail(5)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [ ]:
#4.	Get the total number of rows and columns in the DataFrame.
df2.shape

(20, 11)

In [ ]:
#5.	Display all column names in the dataset.
df2.columns

Index(['PassengerID', 'FirstName', 'LastName', 'Age', 'Gender', 'FlightNumber',
       'Departure', 'Destination', 'TicketPrice', 'SeatClass', 'Status'],
      dtype='object')

In [ ]:
#6.	Get summary statistics of numerical columns.
df2.describe()

       PassengerID        Age  TicketPrice
count     20.00000  20.000000    20.000000
mean      10.50000  33.650000   846.000000
std        5.91608   8.034629   218.352684
min        1.00000  22.000000   500.000000
25%        5.75000  27.750000   692.500000
50%       10.50000  32.500000   825.000000
75%       15.25000  38.500000   955.000000
max       20.00000  50.000000  1300.000000

In [ ]:
#7.	Check for missing values in the dataset Data Selection
df2.isnull().sum()

PassengerID     0
FirstName       0
LastName        0
Age             0
Gender          0
FlightNumber    0
Departure       0
Destination     0
TicketPrice     0
SeatClass       0
Status          0
dtype: int64

In [ ]:
#8.	Select only the 'FirstName' and 'LastName' columns.
df2[['FirstName','LastName']]

   FirstName    LastName
0      Aarav      Sharma
1     Vihaan       Verma
2     Vivaan       Patel
3      Anaya       Desai
4       Myra        Iyer
5      Aryan        Nair
6     Ishaan       Mehta
7      Kabir         Rao
8     Saanvi       Joshi
9     Aadhya        Bhat
10    Advait      Kapoor
11     Rudra      Chopra
12      Pari    Malhotra
13     Kiaan        Jain
14    Tanish     Agarwal
15      Riya        Bose
16   Krishna         Das
17   Shaurya      Saxena
18     Tanvi  Chatterjee
19     Arjun       Gupta

In [ ]:
#9.	Retrieve the ticket price of the 10th passenger.
df2.iloc[9]['TicketPrice']

np.int64(650)

In [ ]:
#Filtering & Sorting
#10.	Find all passengers whose ticket price is greater than ₹900.
df2['TicketPrice'] > 900

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7      True
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15     True
16     True
17    False
18    False
19     True
Name: TicketPrice, dtype: bool

In [ ]:
#11.	Count the number of passengers in each seat class.
df2.groupby('SeatClass')['SeatClass'].count()

SeatClass
Business    7
Economy     9
First       4
Name: SeatClass, dtype: int64

In [ ]:
#12.	Find the passenger with the highest ticket price.
df2.head()
df2[df2['TicketPrice'] == df2['TicketPrice'].max()]

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed

In [ ]:
#13.	Get the average ticket price of all passengers.
df2['TicketPrice'].mean()

np.float64(846.0)

In [ ]:
#14.	Sort the passengers by ticket price in descending order.
df2.sort_values(by='TicketPrice',ascending=False)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold
13,14,Kiaan,Jain,31,Male,QR544,Chennai,Dubai,890,Business,On Hold
5,6,Aryan,Nair,22,Male,LH606,Hyderabad,Munich,850,Economy,Confirmed
14,15,Tanish,Agarwal,35,Male,LH633,Kolkata,Tokyo,800,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
10,11,Advait,Kapoor,32,Male,BA211,Mumbai,London,720,Business,Confirmed
8,9,Saanvi,Joshi,29,Female,UA909,Lucknow,San Francisco,700,Economy,On Hold
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed

In [ ]:
#15.	List all passengers who booked a 'First' class ticket.
df2['SeatClass'] == 'First'

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15     True
16    False
17    False
18    False
19    False
Name: SeatClass, dtype: bool

In [ ]:
#Aggregations & Grouping
#20.	Find the average ticket price per seat class.
df2.groupby('SeatClass')['TicketPrice'].mean()

SeatClass
Business     917.142857
Economy      675.555556
First       1105.000000
Name: TicketPrice, dtype: float64

In [ ]:
#21.	Count the number of passengers in each 'AgeGroup'.
df2.groupby('Age').size().sort_values(ascending=False)

Age
22    1
23    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
38    1
40    1
41    1
45    1
48    1
50    1
dtype: int64

In [ ]:
#22.	Find the highest ticket price in each seat class.
df2.groupby('SeatClass')['TicketPrice'].max()

SeatClass
Business    1150
Economy      850
First       1300
Name: TicketPrice, dtype: int64

In [ ]:
#23.	Find the lowest ticket price in each seat class.
df2.head()
df2.groupby('SeatClass')['TicketPrice'].max()

SeatClass
Business    1150
Economy      850
First       1300
Name: TicketPrice, dtype: int64

In [ ]:
#24.	Find the passenger with the highest age.
df2.head()
df2.groupby('PassengerID')['Age'].max()

PassengerID
1     25
2     30
3     45
4     28
5     34
6     22
7     40
8     38
9     29
10    27
11    32
12    26
13    50
14    31
15    35
16    23
17    36
18    41
19    48
20    33
Name: Age, dtype: int64

In [ ]:
(df2['Status'] == 'Confirmed').count()

np.int64(20)

In [ ]:
df2.head()

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold

In [ ]:
#26.	Find the average ticket price of passengers in Business Class.
df2.head()
(df2['SeatClass'] == 'Business').mean()

np.float64(0.35)

In [ ]:
#27.	Find the highest ticket price for each flight.
df2.head()
df2.groupby('FlightNumber')['TicketPrice'].max()

FlightNumber
AF707     950
AF722     970
AI101     500
AI110     650
AI123     670
BA202     750
BA211     720
DL303     600
DL322     580
EK404    1200
EK433    1300
LH606     850
LH633     800
QR505     900
QR544     890
QR567     910
SQ808    1100
SQ833    1150
UA909     700
UA944     730
Name: TicketPrice, dtype: int64