<a href="https://colab.research.google.com/github/vaishnaviPatil1111/Python/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Dataframe creating
df = pd.read_csv("/content/sales_data.csv")
df

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
8,1009,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
10,1011,Employee_11,46,Electronics,West,26253,49772,No,7,28090.71
11,1012,Employee_12,43,Clothing,North,32197,47360,No,6,34128.82
12,1013,Employee_13,41,Clothing,West,5955,28323,No,6,6312.30
13,1014,Employee_14,50,Electronics,West,30025,34692,No,9,32727.25
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31
15,1016,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
17,1018,Employee_18,31,Home Decor,East,30349,24158,Yes,5,31866.45
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
24,1025,Employee_25,55,Clothing,North,17986,28587,No,7,19245.02
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
27,1028,Employee_28,33,Electronics,West,33593,23312,Yes,5,35272.65
28,1029,Employee_29,44,Clothing,West,7157,10232,No,9,7801.13
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
30,1031,Employee_31,40,Home Decor,West,38718,25399,Yes,7,41428.26
31,1032,Employee_32,54,Clothing,North,34702,47611,No,3,35743.06
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
36,1037,Employee_37,26,Clothing,West,25221,20484,Yes,9,27490.89
37,1038,Employee_38,49,Electronics,North,25613,28763,No,10,28174.30
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
41,1042,Employee_42,37,Home Decor,South,28905,32080,No,9,31506.45
42,1043,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

# **Questions on Sales Data for Pandas:**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#1.	Load the sales data CSV file into a Pandas DataFrame.
df = pd.read_csv("/content/drive/MyDrive/Data Sets/sales_data.csv")
df

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#2.	Display the first 5 rows of the DataFrame.
df.head(5)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08

In [ ]:
#3.	Show the last 5 rows of the DataFrame.
df.tail(5)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#4.	Get the shape (number of rows and columns) of the dataset.
df.shape

(50, 10)

In [ ]:
#5.	Display summary statistics of all numerical columns.
# avg, max, min, std, 1st 2nd 3rd quarter value, count, sum

df.describe()

,EmployeeID,Age,SalesAmount,Target,CommissionPercentage,TotalEarnings
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,1025.50000,39.780000,29381.580000,29492.040000,5.860000,31034.621800
std,14.57738,10.525557,12096.724585,13022.222386,2.432853,12703.757127
min,1001.00000,22.000000,5377.000000,10151.000000,2.000000,5538.310000
25%,1013.25000,31.000000,20736.500000,17249.500000,4.000000,22142.187500
50%,1025.50000,41.000000,29747.000000,28675.000000,6.000000,31686.450000
75%,1037.75000,49.000000,38276.750000,41410.500000,8.000000,40749.962500
max,1050.00000,55.000000,49578.000000,49772.000000,10.000000,52860.600000

In [ ]:
#6.	Get column names of the dataset.
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Department', 'Region', 'SalesAmount',
       'Target', 'TargetAchieved', 'CommissionPercentage', 'TotalEarnings'],
      dtype='object')

In [ ]:
#7.	Check for missing values in the dataset.
df.isnull().sum()

EmployeeID              0
Name                    0
Age                     0
Department              0
Region                  0
SalesAmount             0
Target                  0
TargetAchieved          0
CommissionPercentage    0
TotalEarnings           0
dtype: int64

In [ ]:
#8.	Get the data types of each column.
df.dtypes

EmployeeID                int64
Name                     object
Age                       int64
Department               object
Region                   object
SalesAmount               int64
Target                    int64
TargetAchieved           object
CommissionPercentage      int64
TotalEarnings           float64
dtype: object

In [ ]:
#9.	Sort the dataset by SalesAmount in descending order.
df.sort_values(by='SalesAmount',ascending=False)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
8,1009,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
15,1016,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
42,1043,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
30,1031,Employee_31,40,Home Decor,West,38718,25399,Yes,7,41428.26
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
31,1032,Employee_32,54,Clothing,North,34702,47611,No,3,35743.06
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
27,1028,Employee_28,33,Electronics,West,33593,23312,Yes,5,35272.65
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
11,1012,Employee_12,43,Clothing,North,32197,47360,No,6,34128.82
17,1018,Employee_18,31,Home Decor,East,30349,24158,Yes,5,31866.45
13,1014,Employee_14,50,Electronics,West,30025,34692,No,9,32727.25
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
41,1042,Employee_42,37,Home Decor,South,28905,32080,No,9,31506.45
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
10,1011,Employee_11,46,Electronics,West,26253,49772,No,7,28090.71
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
37,1038,Employee_38,49,Electronics,North,25613,28763,No,10,28174.30
36,1037,Employee_37,26,Clothing,West,25221,20484,Yes,9,27490.89
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
24,1025,Employee_25,55,Clothing,North,17986,28587,No,7,19245.02
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
28,1029,Employee_29,44,Clothing,West,7157,10232,No,9,7801.13
12,1013,Employee_13,41,Clothing,West,5955,28323,No,6,6312.30
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31

In [ ]:
#10.	Select only EmployeeID, Name, and SalesAmount columns.
df[['EmployeeID', 'Name', 'SalesAmount']]

    EmployeeID         Name  SalesAmount
0         1001   Employee_1        34200
1         1002   Employee_2        32850
2         1003   Employee_3        43267
3         1004   Employee_4        17263
4         1005   Employee_5        37427
5         1006   Employee_6        25853
6         1007   Employee_7         7695
7         1008   Employee_8        47690
8         1009   Employee_9        49578
9         1010  Employee_10        18766
10        1011  Employee_11        26253
11        1012  Employee_12        32197
12        1013  Employee_13         5955
13        1014  Employee_14        30025
14        1015  Employee_15         5377
15        1016  Employee_16        48945
16        1017  Employee_17        40326
17        1018  Employee_18        30349
18        1019  Employee_19        12766
19        1020  Employee_20        28150
20        1021  Employee_21        27366
21        1022  Employee_22         8939
22        1023  Employee_23        41728
23        1024  Employee_24        36688
24        1025  Employee_25        17986
25        1026  Employee_26        21533
26        1027  Employee_27        38560
27        1028  Employee_28        33593
28        1029  Employee_29         7157
29        1030  Employee_30        27787
30        1031  Employee_31        38718
31        1032  Employee_32        34702
32        1033  Employee_33        29469
33        1034  Employee_34        49111
34        1035  Employee_35        39717
35        1036  Employee_36        20471
36        1037  Employee_37        25221
37        1038  Employee_38        25613
38        1039  Employee_39        35710
39        1040  Employee_40        27167
40        1041  Employee_41        44983
41        1042  Employee_42        28905
42        1043  Employee_43        46558
43        1044  Employee_44        11767
44        1045  Employee_45        40454
45        1046  Employee_46        32685
46        1047  Employee_47        37045
47        1048  Employee_48        18960
48        1049  Employee_49        17997
49        1050  Employee_50        27557