<a href="https://colab.research.google.com/github/vaishnaviPatil1111/Python/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Exploration Questions:**

In [ ]:
import numpy as np
import pandas as pd

## ***Questions on Sales Data for Pandas:***

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#1.	Load the sales data CSV file into a Pandas DataFrame.
df = pd.read_csv("/content/drive/MyDrive/Data Sets/sales_data.csv")
df

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
8,1009,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
10,1011,Employee_11,46,Electronics,West,26253,49772,No,7,28090.71
11,1012,Employee_12,43,Clothing,North,32197,47360,No,6,34128.82
12,1013,Employee_13,41,Clothing,West,5955,28323,No,6,6312.30
13,1014,Employee_14,50,Electronics,West,30025,34692,No,9,32727.25
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31
15,1016,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
17,1018,Employee_18,31,Home Decor,East,30349,24158,Yes,5,31866.45
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
24,1025,Employee_25,55,Clothing,North,17986,28587,No,7,19245.02
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
27,1028,Employee_28,33,Electronics,West,33593,23312,Yes,5,35272.65
28,1029,Employee_29,44,Clothing,West,7157,10232,No,9,7801.13
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
30,1031,Employee_31,40,Home Decor,West,38718,25399,Yes,7,41428.26
31,1032,Employee_32,54,Clothing,North,34702,47611,No,3,35743.06
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
36,1037,Employee_37,26,Clothing,West,25221,20484,Yes,9,27490.89
37,1038,Employee_38,49,Electronics,North,25613,28763,No,10,28174.30
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
41,1042,Employee_42,37,Home Decor,South,28905,32080,No,9,31506.45
42,1043,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#2.	Display the first 5 rows of the DataFrame.
df.head(5)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08

In [ ]:
#3.	Show the last 5 rows of the DataFrame.
df.tail(5)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#4.	Get the shape (number of rows and columns) of the dataset.
df.shape

(50, 10)

In [ ]:
#5.	Display summary statistics of all numerical columns.
# avg, max, min, std, 1st 2nd 3rd quarter value, count, sum

df.describe()

,EmployeeID,Age,SalesAmount,Target,CommissionPercentage,TotalEarnings
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,1025.50000,39.780000,29381.580000,29492.040000,5.860000,31034.621800
std,14.57738,10.525557,12096.724585,13022.222386,2.432853,12703.757127
min,1001.00000,22.000000,5377.000000,10151.000000,2.000000,5538.310000
25%,1013.25000,31.000000,20736.500000,17249.500000,4.000000,22142.187500
50%,1025.50000,41.000000,29747.000000,28675.000000,6.000000,31686.450000
75%,1037.75000,49.000000,38276.750000,41410.500000,8.000000,40749.962500
max,1050.00000,55.000000,49578.000000,49772.000000,10.000000,52860.600000

In [ ]:
#6.	Get column names of the dataset.
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Department', 'Region', 'SalesAmount',
       'Target', 'TargetAchieved', 'CommissionPercentage', 'TotalEarnings'],
      dtype='object')

In [ ]:
#7.	Check for missing values in the dataset.
df.isnull().sum()

EmployeeID              0
Name                    0
Age                     0
Department              0
Region                  0
SalesAmount             0
Target                  0
TargetAchieved          0
CommissionPercentage    0
TotalEarnings           0
dtype: int64

In [ ]:
#8.	Get the data types of each column.
df.dtypes

EmployeeID                int64
Name                     object
Age                       int64
Department               object
Region                   object
SalesAmount               int64
Target                    int64
TargetAchieved           object
CommissionPercentage      int64
TotalEarnings           float64
dtype: object

In [ ]:
#9.	Sort the dataset by SalesAmount in descending order.
df.sort_values(by='SalesAmount',ascending=False)

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
8,1009,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
15,1016,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
42,1043,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
2,1003,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
30,1031,Employee_31,40,Home Decor,West,38718,25399,Yes,7,41428.26
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
46,1047,Employee_47,31,Clothing,East,37045,10613,Yes,9,40379.05
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
31,1032,Employee_32,54,Clothing,North,34702,47611,No,3,35743.06
0,1001,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00
27,1028,Employee_28,33,Electronics,West,33593,23312,Yes,5,35272.65
1,1002,Employee_2,26,Home Decor,East,32850,42821,No,9,35806.50
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
11,1012,Employee_12,43,Clothing,North,32197,47360,No,6,34128.82
17,1018,Employee_18,31,Home Decor,East,30349,24158,Yes,5,31866.45
13,1014,Employee_14,50,Electronics,West,30025,34692,No,9,32727.25
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
41,1042,Employee_42,37,Home Decor,South,28905,32080,No,9,31506.45
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
10,1011,Employee_11,46,Electronics,West,26253,49772,No,7,28090.71
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
37,1038,Employee_38,49,Electronics,North,25613,28763,No,10,28174.30
36,1037,Employee_37,26,Clothing,West,25221,20484,Yes,9,27490.89
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85
24,1025,Employee_25,55,Clothing,North,17986,28587,No,7,19245.02
3,1004,Employee_4,31,Electronics,West,17263,40183,No,3,17780.89
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
28,1029,Employee_29,44,Clothing,West,7157,10232,No,9,7801.13
12,1013,Employee_13,41,Clothing,West,5955,28323,No,6,6312.30
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31

In [ ]:
#10.	Select only EmployeeID, Name, and SalesAmount columns.
df[['EmployeeID', 'Name', 'SalesAmount']]

    EmployeeID         Name  SalesAmount
0         1001   Employee_1        34200
1         1002   Employee_2        32850
2         1003   Employee_3        43267
3         1004   Employee_4        17263
4         1005   Employee_5        37427
5         1006   Employee_6        25853
6         1007   Employee_7         7695
7         1008   Employee_8        47690
8         1009   Employee_9        49578
9         1010  Employee_10        18766
10        1011  Employee_11        26253
11        1012  Employee_12        32197
12        1013  Employee_13         5955
13        1014  Employee_14        30025
14        1015  Employee_15         5377
15        1016  Employee_16        48945
16        1017  Employee_17        40326
17        1018  Employee_18        30349
18        1019  Employee_19        12766
19        1020  Employee_20        28150
20        1021  Employee_21        27366
21        1022  Employee_22         8939
22        1023  Employee_23        41728
23        1024  Employee_24        36688
24        1025  Employee_25        17986
25        1026  Employee_26        21533
26        1027  Employee_27        38560
27        1028  Employee_28        33593
28        1029  Employee_29         7157
29        1030  Employee_30        27787
30        1031  Employee_31        38718
31        1032  Employee_32        34702
32        1033  Employee_33        29469
33        1034  Employee_34        49111
34        1035  Employee_35        39717
35        1036  Employee_36        20471
36        1037  Employee_37        25221
37        1038  Employee_38        25613
38        1039  Employee_39        35710
39        1040  Employee_40        27167
40        1041  Employee_41        44983
41        1042  Employee_42        28905
42        1043  Employee_43        46558
43        1044  Employee_44        11767
44        1045  Employee_45        40454
45        1046  Employee_46        32685
46        1047  Employee_47        37045
47        1048  Employee_48        18960
48        1049  Employee_49        17997
49        1050  Employee_50        27557

In [ ]:
#*Filtering & Conditional Selection ( SQL limit , Sort asc desc , Where )*
#11.	Find all employees who achieved their sales target.
df.head()
df['TargetAchieved']=='yes'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: TargetAchieved, dtype: bool

In [ ]:
#12.	Find employees who belong to the "Electronics" department.
df['Department']=='Electronics'

0      True
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13     True
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28    False
29    False
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44     True
45    False
46    False
47    False
48    False
49    False
Name: Department, dtype: bool

In [ ]:
#13.	Find employees who belong to the "West" region and achieved their target.
df['Region']=='West'

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
12     True
13     True
14    False
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28     True
29     True
30     True
31    False
32    False
33    False
34    False
35     True
36     True
37    False
38     True
39     True
40    False
41    False
42     True
43     True
44    False
45    False
46    False
47    False
48    False
49    False
Name: Region, dtype: bool

In [ ]:
#14.	Filter employees who have a SalesAmount greater than 30,000.
df['SalesAmount']>30000

0      True
1      True
2      True
3     False
4      True
5     False
6     False
7      True
8      True
9     False
10    False
11     True
12    False
13     True
14    False
15     True
16     True
17     True
18    False
19    False
20    False
21    False
22     True
23     True
24    False
25    False
26     True
27     True
28    False
29    False
30     True
31     True
32    False
33     True
34     True
35    False
36    False
37    False
38     True
39    False
40     True
41    False
42     True
43    False
44     True
45     True
46     True
47    False
48    False
49    False
Name: SalesAmount, dtype: bool

In [ ]:
#15.	Find employees who have a commission percentage greater than 5%.
df.head()
df['CommissionPercentage'] > 5

0     False
1      True
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9     False
10     True
11     True
12     True
13     True
14    False
15     True
16     True
17    False
18     True
19    False
20    False
21     True
22     True
23    False
24     True
25     True
26     True
27    False
28     True
29     True
30     True
31    False
32    False
33     True
34    False
35     True
36     True
37     True
38     True
39    False
40    False
41     True
42     True
43     True
44    False
45    False
46     True
47     True
48    False
49    False
Name: CommissionPercentage, dtype: bool

In [ ]:
#16.	Find employees who did not achieve their target.
df['TargetAchieved'] == 'No'

0     False
1      True
2     False
3      True
4     False
5      True
6      True
7      True
8     False
9     False
10     True
11     True
12     True
13     True
14     True
15    False
16     True
17    False
18     True
19    False
20    False
21     True
22    False
23    False
24     True
25     True
26     True
27    False
28     True
29     True
30    False
31     True
32    False
33    False
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41     True
42    False
43     True
44    False
45     True
46    False
47    False
48    False
49    False
Name: TargetAchieved, dtype: bool

In [ ]:
#17.	Find employees who belong to either "Groceries" or "Automobile" department.
df[(df['Department'] == 'Groceries') | (df['Department'] == 'Automobile')]

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
5,1006,Employee_6,22,Groceries,East,25853,41898,No,4,26887.12
6,1007,Employee_7,43,Automobile,West,7695,32586,No,10,8464.50
7,1008,Employee_8,37,Groceries,South,47690,49267,No,3,49120.70
14,1015,Employee_15,47,Groceries,South,5377,16274,No,3,5538.31
16,1017,Employee_17,23,Groceries,East,40326,47702,No,6,42745.56
18,1019,Employee_19,55,Automobile,North,12766,48762,No,9,13914.94
19,1020,Employee_20,36,Automobile,West,28150,15865,Yes,4,29276.00
21,1022,Employee_22,32,Groceries,East,8939,31223,No,8,9654.12
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
25,1026,Employee_26,55,Automobile,South,21533,47125,No,9,23470.97
26,1027,Employee_27,31,Groceries,East,38560,47726,No,6,40873.60
29,1030,Employee_30,23,Groceries,West,27787,41638,No,6,29454.22
35,1036,Employee_36,30,Groceries,West,20471,35198,No,6,21699.26
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
40,1041,Employee_41,32,Automobile,East,44983,24131,Yes,3,46332.49
43,1044,Employee_44,53,Automobile,West,11767,38819,No,7,12590.69
45,1046,Employee_46,51,Automobile,North,32685,48545,No,2,33338.70
47,1048,Employee_48,35,Groceries,East,18960,12567,Yes,8,20476.80
49,1050,Employee_50,33,Automobile,North,27557,13555,Yes,5,28934.85

In [ ]:
#18.	Find employees with TotalEarnings greater than 40,000.
df['TotalEarnings'] > 40000

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30     True
31    False
32    False
33     True
34     True
35    False
36    False
37    False
38    False
39    False
40     True
41    False
42     True
43    False
44     True
45    False
46     True
47    False
48    False
49    False
Name: TotalEarnings, dtype: bool

In [ ]:
#19.	Find employees who are older than 40 years and achieved their target.
df.head()
df[(df['Age'] > 40) & (df['TargetAchieved'] == 'Yes')]

,EmployeeID,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings
4,1005,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08
9,1010,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64
20,1021,Employee_21,51,Clothing,North,27366,14747,Yes,5,28734.30
22,1023,Employee_23,47,Automobile,East,41728,19652,Yes,9,45483.52
23,1024,Employee_24,52,Automobile,North,36688,33729,Yes,3,37788.64
32,1033,Employee_33,49,Clothing,North,29469,10151,Yes,2,30058.38
33,1034,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66
34,1035,Employee_35,41,Clothing,North,39717,12490,Yes,3,40908.51
38,1039,Employee_39,55,Clothing,West,35710,34422,Yes,6,37852.60
39,1040,Employee_40,44,Automobile,West,27167,25440,Yes,3,27982.01
44,1045,Employee_45,53,Electronics,East,40454,19416,Yes,2,41263.08
48,1049,Employee_49,43,Home Decor,South,17997,12104,Yes,5,18896.85

In [ ]:
#20.	Select employees whose names contain "10".
df['Name'].str.contains('10')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Name, dtype: bool

In [ ]:
#Aggregation & Grouping (Pivot , Group by )
#21.	Find the average sales amount per department.
df.groupby('Department')['SalesAmount'].mean()

Department
Automobile     26610.818182
Clothing       26593.181818
Electronics    32422.300000
Groceries      27139.000000
Home Decor     36027.750000
Name: SalesAmount, dtype: float64

In [ ]:
#22.	Count the number of employees in each region.
df.groupby('Region')['EmployeeID'].count()

Region
East     16
North    12
South     6
West     16
Name: EmployeeID, dtype: int64

In [ ]:
#23.	Find the highest SalesAmount in each department.
df.head()
df.groupby('Department')['SalesAmount'].max()

Department
Automobile     44983
Clothing       39717
Electronics    49111
Groceries      47690
Home Decor     49578
Name: SalesAmount, dtype: int64

In [ ]:
#24.	Find the lowest SalesAmount in each department.
df.groupby('Department')['SalesAmount'].min()

Department
Automobile      7695
Clothing        5955
Electronics    17263
Groceries       5377
Home Decor     17997
Name: SalesAmount, dtype: int64

In [ ]:
#25.	Find the employee with the highest total earnings.
df.head()
df.groupby('TotalEarnings')['EmployeeID'].max()

TotalEarnings
5538.31     1015
6312.30     1013
7801.13     1029
8464.50     1007
9654.12     1022
12590.69    1044
13914.94    1019
17780.89    1004
18896.85    1049
19245.02    1025
19516.64    1010
20476.80    1048
21699.26    1036
23470.97    1026
26887.12    1006
27490.89    1037
27982.01    1040
28090.71    1011
28174.30    1038
28734.30    1021
28934.85    1050
29276.00    1020
29454.22    1030
30058.38    1033
31506.45    1042
31866.45    1018
32727.25    1014
33338.70    1046
34128.82    1012
35272.65    1028
35743.06    1032
35806.50    1002
35910.00    1001
37788.64    1024
37852.60    1039
38924.08    1005
40379.05    1047
40873.60    1027
40908.51    1035
41263.08    1045
41428.26    1031
42745.56    1017
44132.34    1003
45483.52    1023
46332.49    1041
49120.70    1008
50282.64    1043
52057.66    1034
52552.68    1009
52860.60    1016
Name: EmployeeID, dtype: int64

In [ ]:
#26.	Count the number of employees who achieved and did not achieve their target.
df.head()
df.groupby('TargetAchieved')['EmployeeID'].count()

TargetAchieved
No     24
Yes    26
Name: EmployeeID, dtype: int64

In [ ]:
#27.	Find the average commission percentage per department.
df.groupby('Department')['CommissionPercentage'].mean()

Department
Automobile     5.818182
Clothing       5.909091
Electronics    5.900000
Groceries      5.400000
Home Decor     6.375000
Name: CommissionPercentage, dtype: float64

In [ ]:
#28.	Find the highest TotalEarnings per region.
df.head()
df.groupby('Region')['TotalEarnings'].max()

Region
East     52860.60
North    40908.51
South    49120.70
West     50282.64
Name: TotalEarnings, dtype: float64

In [ ]:
#29.	Find the lowest TotalEarnings per department.
df.groupby('Region')['TotalEarnings'].min()

Region
East      9654.12
North    13914.94
South     5538.31
West      6312.30
Name: TotalEarnings, dtype: float64

In [ ]:
#30.	Count the number of employees per department
df.groupby('Department')['EmployeeID'].count()

Department
Automobile     11
Clothing       11
Electronics    10
Groceries      10
Home Decor      8
Name: EmployeeID, dtype: int64

In [ ]:
#Data Transformation
#31.	Remove the EmployeeID column from the DataFrame.
df.drop(columns=['EmployeeID'],inplace=True)

KeyError: "['EmployeeID'] not found in axis"

In [ ]:
#32.	Reset the index of the DataFrame.
df.reset_index(drop=True,inplace=True)

In [ ]:
#33.	Replace all employees who did not achieve the target with "Needs Improvement" in the TargetAchieved column.
df['TargetAchieved'].replace('No','Needs Improvement',inplace=True)

/tmp/ipykernel_1120/2137185450.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TargetAchieved'].replace('No','Needs Improvement',inplace=True)

In [ ]:
#34.	Create a new column PerformanceLevel with values: "High" if SalesAmount > 40000, "Medium" if between 20000-40000, else "Low".
df['PerformanceLevel'] = df['SalesAmount'].apply(lambda i: 'High' if i > 40000 else ('Medium' if i > 20000 else 'Low'))

In [ ]:
#35.	Convert Age column to an integer type.
df['Age']=df['Age'].astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  50 non-null     object
 1   Age                   50 non-null     int64
 2   Department            50 non-null     category
 3   Region                50 non-null     object
 4   SalesAmount           50 non-null     int64
 5   Target                50 non-null     int64
 6   TargetAchieved        50 non-null     object
 7   CommissionPercentage  50 non-null     int64
 8   TotalEarnings         50 non-null     float64
 9   PerformanceLevel      50 non-null     object
 10  AboveAverageEarnings  50 non-null     object
dtypes: category(1), float64(1), int64(4), object(5)
memory usage: 4.3+ KB

In [ ]:
#36.	Create a new column AboveAverageEarnings, which is "Yes" if TotalEarnings is above the average.
avg_earning= df['TotalEarnings'].mean()
df['AboveAverageEarnings']=df['TotalEarnings'].apply(lambda x: 'Yes' if x > avg_earning else 'No')

In [ ]:
df.head()

,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings,PerformanceLevel,AboveAverageEarnings
0,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00,Medium,Yes
1,Employee_2,26,Home Decor,East,32850,42821,Needs Improvement,9,35806.50,Medium,Yes
2,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34,High,Yes
3,Employee_4,31,Electronics,West,17263,40183,Needs Improvement,3,17780.89,Low,No
4,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08,Medium,Yes

In [ ]:
#37.	Convert the Department column to a categorical data type.
df['Department'] = df['Department'].astype('category')

In [ ]:
#38.	Find the top 5 employees based on total earnings.
df.sort_values(by='TotalEarnings',ascending=False).head(5)

,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings,PerformanceLevel,AboveAverageEarnings
15,Employee_16,22,Electronics,East,48945,44965,Yes,8,52860.60,High,Yes
8,Employee_9,31,Home Decor,East,49578,22738,Yes,6,52552.68,High,Yes
33,Employee_34,42,Electronics,East,49111,31797,Yes,6,52057.66,High,Yes
42,Employee_43,33,Home Decor,West,46558,15582,Yes,8,50282.64,High,Yes
7,Employee_8,37,Groceries,South,47690,49267,Needs Improvement,3,49120.70,High,Yes

In [ ]:
#39.	Find the bottom 5 employees based on total earnings.
df.sort_values(by='TotalEarnings',ascending=False).tail(5)

,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings,PerformanceLevel,AboveAverageEarnings
21,Employee_22,32,Groceries,East,8939,31223,Needs Improvement,8,9654.12,Low,No
6,Employee_7,43,Automobile,West,7695,32586,Needs Improvement,10,8464.50,Low,No
28,Employee_29,44,Clothing,West,7157,10232,Needs Improvement,9,7801.13,Low,No
12,Employee_13,41,Clothing,West,5955,28323,Needs Improvement,6,6312.30,Low,No
14,Employee_15,47,Groceries,South,5377,16274,Needs Improvement,3,5538.31,Low,No

In [ ]:
#40.	Save the modified DataFrame to a new CSV file.
df.to_csv('modified_sales_data.csv',index=False)

## ***Questions on Cars Data for Pandas:***

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Data Sets/cars_data (1).csv")
df1

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
0,1,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941
1,2,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006
2,3,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970
3,4,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880
4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077
5,6,Ford,Explorer,2011,77712,Diesel,41.56,405,341,4,Manual,No,North,2,68106
6,7,Honda,Pilot,2013,10300,Diesel,17.70,275,332,4,Manual,Yes,South,4,7139
7,8,Toyota,Prius,2012,17388,Petrol,45.71,378,156,5,Manual,No,South,5,10033
8,9,Mercedes,GLE,2013,25585,Electric,24.16,326,309,4,Automatic,No,South,1,18884
9,10,Ford,Explorer,2012,37985,Diesel,37.34,239,473,4,Automatic,No,West,2,32984
10,11,Ford,Fiesta,2019,67254,Petrol,15.29,134,480,7,Automatic,Yes,South,3,52939
11,12,Honda,Civic,2020,64608,Electric,10.61,564,332,5,Manual,No,North,5,45789
12,13,Mercedes,E-Class,2012,29315,Electric,26.83,352,206,7,Manual,Yes,East,1,14665
13,14,Honda,CR-V,2022,30202,Petrol,39.59,475,312,2,Manual,No,East,1,16262
14,15,Honda,Civic,2015,34824,Electric,37.11,377,289,4,Manual,Yes,West,3,21668
15,16,Ford,Focus,2019,43068,Electric,19.92,249,389,5,Manual,Yes,West,3,27690
16,17,Toyota,Highlander,2020,71536,Petrol,37.93,493,458,7,Manual,No,South,2,50319
17,18,Ford,Fiesta,2020,63321,Diesel,24.16,407,489,4,Automatic,No,North,1,46879
18,19,Mercedes,GLC,2013,50248,Diesel,46.46,230,658,2,Manual,No,East,4,27816
19,20,Honda,Civic,2017,37778,Petrol,24.12,563,163,2,Manual,No,South,2,32158
20,21,Honda,CR-V,2014,46256,Petrol,16.72,266,255,2,Manual,Yes,East,3,32004
21,22,Mercedes,GLC,2017,66352,Petrol,43.12,156,516,7,Manual,Yes,East,5,52467
22,23,Mercedes,C-Class,2021,35241,Electric,33.54,538,342,2,Manual,Yes,East,2,22622
23,24,Toyota,Camry,2013,28883,Petrol,38.70,213,233,2,Automatic,Yes,South,5,19527
24,25,Ford,Mustang,2011,62600,Diesel,48.76,496,439,4,Automatic,No,West,4,45733
25,26,BMW,X3,2010,24263,Electric,13.32,200,415,2,Automatic,Yes,South,5,15836
26,27,Mercedes,S-Class,2013,27977,Petrol,46.51,300,160,5,Automatic,Yes,West,4,17662
27,28,Toyota,Corolla,2010,62300,Petrol,34.26,145,454,4,Manual,No,East,3,37752
28,29,Ford,F-150,2020,30749,Electric,14.78,556,155,2,Manual,No,South,2,19501
29,30,Toyota,RAV4,2015,36720,Diesel,40.73,147,484,2,Automatic,No,North,1,24917
30,31,Honda,Fit,2015,38883,Diesel,46.20,565,150,7,Manual,No,West,3,31463
31,32,Mercedes,C-Class,2012,25800,Petrol,45.72,359,291,5,Automatic,No,South,3,18886
32,33,Ford,Fiesta,2018,56907,Electric,30.46,506,322,4,Manual,Yes,West,1,49844
33,34,Mercedes,GLE,2023,75933,Diesel,12.74,244,399,4,Manual,Yes,East,5,63652
34,35,Ford,Fiesta,2021,77675,Diesel,38.46,118,496,5,Automatic,No,North,4,66231
35,36,BMW,3 Series,2010,54825,Diesel,20.94,579,491,5,Automatic,No,West,1,40647
36,37,BMW,X3,2013,29725,Petrol,44.13,235,312,7,Automatic,Yes,South,1,18958
37,38,Toyota,Prius,2018,64805,Electric,31.16,231,210,5,Automatic,No,South,3,40083
38,39,Toyota,Camry,2016,20997,Petrol,31.47,107,688,5,Manual,Yes,South,1,14372
39,40,Toyota,RAV4,2022,68178,Petrol,25.01,134,612,7,Manual,No,West,1,43926
40,41,Honda,Pilot,2018,76039,Diesel,27.92,498,509,7,Manual,No,North,2,59039
41,42,Ford,Focus,2020,16659,Petrol,26.08,508,496,4,Manual,No,East,5,14128
42,43,Honda,Fit,2014,39685,Diesel,49.65,195,266,2,Automatic,Yes,South,2,27197
43,44,BMW,X5,2023,60310,Petrol,14.98,215,375,2,Automatic,Yes,North,3,53420
44,45,Mercedes,S-Class,2012,69705,Petrol,16.50,422,586,4,Automatic,Yes,West,5,50597
45,46,Ford,Explorer,2016,17051,Electric,38.91,558,193,5,Manual,No,West,1,11446
46,47,Honda,Accord,2015,49903,Diesel,37.78,243,472,5,Automatic,No,North,5,33468
47,48,Toyota,Highlander,2016,25138,Petrol,49.10,280,202,4,Automatic,No,West,2,22109
48,49,Toyota,Camry,2014,39294,Petrol,36.95,506,362,5,Manual,Yes,North,1,20293
49,50,BMW,5 Series,2014,28773,Diesel,44.83,248,252,2,Manual,Yes,South,1,25545

In [ ]:
# 1.	Display the first 5 rows of the dataset.
df1.head(5)

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
0,1,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941
1,2,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006
2,3,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970
3,4,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880
4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077

In [ ]:
# 2.	Show the last 5 rows of the dataset.
df1.tail(5)

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
45,46,Ford,Explorer,2016,17051,Electric,38.91,558,193,5,Manual,No,West,1,11446
46,47,Honda,Accord,2015,49903,Diesel,37.78,243,472,5,Automatic,No,North,5,33468
47,48,Toyota,Highlander,2016,25138,Petrol,49.10,280,202,4,Automatic,No,West,2,22109
48,49,Toyota,Camry,2014,39294,Petrol,36.95,506,362,5,Manual,Yes,North,1,20293
49,50,BMW,5 Series,2014,28773,Diesel,44.83,248,252,2,Manual,Yes,South,1,25545

In [ ]:
# 3.	Get the shape (number of rows and columns) of the dataset.
df1.shape

(50, 15)

In [ ]:
# 4.	Display summary statistics for all numerical columns.
df1.describe()

,CarID,Year,Price,Mileage,Horsepower,Torque,Seats,SafetyRating,ResaleValue
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,25.50000,2015.880000,45147.320000,32.278200,324.760000,361.700000,4.220000,2.720000,33150.600000
std,14.57738,3.847289,19667.845968,11.848107,151.517974,139.352914,1.729575,1.512398,16788.502376
min,1.00000,2010.000000,10300.000000,10.610000,107.000000,150.000000,2.000000,1.000000,7139.000000
25%,13.25000,2013.000000,28991.000000,21.915000,213.500000,257.750000,2.000000,1.000000,19129.750000
50%,25.50000,2015.000000,39489.500000,35.605000,277.500000,336.500000,4.000000,2.500000,29393.000000
75%,37.75000,2019.750000,63140.750000,42.237500,488.500000,478.250000,5.000000,4.000000,46606.500000
max,50.00000,2023.000000,79402.000000,49.650000,579.000000,688.000000,7.000000,5.000000,68941.000000

In [ ]:
# 5.	Get the column names of the dataset.
df1.columns

Index(['CarID', 'Brand', 'Model', 'Year', 'Price', 'FuelType', 'Mileage',
       'Horsepower', 'Torque', 'Seats', 'Transmission', 'Sold', 'Region',
       'SafetyRating', 'ResaleValue'],
      dtype='object')

In [ ]:
# 6.	Check for missing values in the dataset.
df1.isnull().sum()

CarID           0
Brand           0
Model           0
Year            0
Price           0
FuelType        0
Mileage         0
Horsepower      0
Torque          0
Seats           0
Transmission    0
Sold            0
Region          0
SafetyRating    0
ResaleValue     0
dtype: int64

In [ ]:
# 7.	Get the data types of each column Filtering and Sorting Questions
df1.dtypes

CarID             int64
Brand            object
Model            object
Year              int64
Price             int64
FuelType         object
Mileage         float64
Horsepower        int64
Torque            int64
Seats             int64
Transmission     object
Sold             object
Region           object
SafetyRating      int64
ResaleValue       int64
dtype: object

In [ ]:
# 8.	Sort the dataset by Price in descending order.
df1[['Price']].sort_values(by='Price',ascending=False)

    Price
0   79402
5   77712
34  77675
40  76039
33  75933
16  71536
44  69705
39  68178
10  67254
21  66352
37  64805
11  64608
17  63321
24  62600
27  62300
43  60310
4   59752
32  56907
35  54825
18  50248
46  49903
20  46256
15  43068
2   40886
42  39685
48  39294
30  38883
9   37985
19  37778
29  36720
22  35241
14  34824
3   34459
28  30749
13  30202
36  29725
12  29315
23  28883
49  28773
26  27977
31  25800
8   25585
47  25138
25  24263
1   24117
38  20997
7   17388
45  17051
41  16659
6   10300

In [ ]:
# 9.	Select only the Brand, Model, and Price columns.
df1[['Brand','Model','Price']]

       Brand       Model  Price
0        BMW    5 Series  79402
1   Mercedes     E-Class  24117
2   Mercedes         GLC  40886
3      Honda        CR-V  34459
4   Mercedes     C-Class  59752
5       Ford    Explorer  77712
6      Honda       Pilot  10300
7     Toyota       Prius  17388
8   Mercedes         GLE  25585
9       Ford    Explorer  37985
10      Ford      Fiesta  67254
11     Honda       Civic  64608
12  Mercedes     E-Class  29315
13     Honda        CR-V  30202
14     Honda       Civic  34824
15      Ford       Focus  43068
16    Toyota  Highlander  71536
17      Ford      Fiesta  63321
18  Mercedes         GLC  50248
19     Honda       Civic  37778
20     Honda        CR-V  46256
21  Mercedes         GLC  66352
22  Mercedes     C-Class  35241
23    Toyota       Camry  28883
24      Ford     Mustang  62600
25       BMW          X3  24263
26  Mercedes     S-Class  27977
27    Toyota     Corolla  62300
28      Ford       F-150  30749
29    Toyota        RAV4  36720
30     Honda         Fit  38883
31  Mercedes     C-Class  25800
32      Ford      Fiesta  56907
33  Mercedes         GLE  75933
34      Ford      Fiesta  77675
35       BMW    3 Series  54825
36       BMW          X3  29725
37    Toyota       Prius  64805
38    Toyota       Camry  20997
39    Toyota        RAV4  68178
40     Honda       Pilot  76039
41      Ford       Focus  16659
42     Honda         Fit  39685
43       BMW          X5  60310
44  Mercedes     S-Class  69705
45      Ford    Explorer  17051
46     Honda      Accord  49903
47    Toyota  Highlander  25138
48    Toyota       Camry  39294
49       BMW    5 Series  28773

In [ ]:
#Filtering and Sorting Questions
#10.	Find all cars that have been sold.
df1['Sold'] == 'Yes'

0      True
1      True
2      True
3      True
4      True
5     False
6      True
7     False
8     False
9     False
10     True
11    False
12     True
13    False
14     True
15     True
16    False
17    False
18    False
19    False
20     True
21     True
22     True
23     True
24    False
25     True
26     True
27    False
28    False
29    False
30    False
31    False
32     True
33     True
34    False
35    False
36     True
37    False
38     True
39    False
40    False
41    False
42     True
43     True
44     True
45    False
46    False
47    False
48     True
49     True
Name: Sold, dtype: bool

In [ ]:
#11.	Find all cars that belong to the "BMW" brand.
df1['Brand'] == 'BMW'

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35     True
36     True
37    False
38    False
39    False
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49     True
Name: Brand, dtype: bool

In [ ]:
#12.	Find all cars that are from the year 2020 or later.
df1['Year'] >= 2020

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13     True
14    False
15    False
16     True
17     True
18    False
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34     True
35    False
36    False
37    False
38    False
39     True
40    False
41     True
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49    False
Name: Year, dtype: bool

In [ ]:
#13.	Find all cars that belong to the "North" region and have been sold.
df1.head()
df1[(df1['Region'] == 'North') & (df1['Sold'] == 'Yes')]

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077
43,44,BMW,X5,2023,60310,Petrol,14.98,215,375,2,Automatic,Yes,North,3,53420
48,49,Toyota,Camry,2014,39294,Petrol,36.95,506,362,5,Manual,Yes,North,1,20293

In [ ]:
#14.	Filter cars that have Price greater than $40,000.
df1['Price'] > 40000

0      True
1     False
2      True
3     False
4      True
5      True
6     False
7     False
8     False
9     False
10     True
11     True
12    False
13    False
14    False
15     True
16     True
17     True
18     True
19    False
20     True
21     True
22    False
23    False
24     True
25    False
26    False
27     True
28    False
29    False
30    False
31    False
32     True
33     True
34     True
35     True
36    False
37     True
38    False
39     True
40     True
41    False
42    False
43     True
44     True
45    False
46     True
47    False
48    False
49    False
Name: Price, dtype: bool

In [ ]:
#15.	Find all cars with Horsepower greater than 300.
df1['Horsepower'] > 300

0      True
1     False
2     False
3     False
4     False
5      True
6     False
7      True
8      True
9     False
10    False
11     True
12     True
13     True
14     True
15    False
16     True
17     True
18    False
19     True
20    False
21    False
22     True
23    False
24     True
25    False
26    False
27    False
28     True
29    False
30     True
31     True
32     True
33    False
34    False
35     True
36    False
37    False
38    False
39    False
40     True
41     True
42    False
43    False
44     True
45     True
46    False
47    False
48     True
49    False
Name: Horsepower, dtype: bool

In [ ]:
#16.	Find all cars with a Mileage greater than 30 MPG.
df1['Mileage'] > 30

0      True
1     False
2      True
3      True
4     False
5      True
6     False
7      True
8     False
9      True
10    False
11    False
12    False
13     True
14     True
15    False
16     True
17    False
18     True
19    False
20    False
21     True
22     True
23     True
24     True
25    False
26     True
27     True
28    False
29     True
30     True
31     True
32     True
33    False
34     True
35    False
36     True
37     True
38     True
39    False
40    False
41    False
42     True
43    False
44    False
45     True
46     True
47     True
48     True
49     True
Name: Mileage, dtype: bool

In [ ]:
#17.	Find all cars that have an automatic transmission.
df1['Transmission'] == 'Automatic'

0     False
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23     True
24     True
25     True
26     True
27    False
28    False
29     True
30    False
31     True
32    False
33    False
34     True
35     True
36     True
37     True
38    False
39    False
40    False
41    False
42     True
43     True
44     True
45    False
46     True
47     True
48    False
49    False
Name: Transmission, dtype: bool

In [ ]:
#18.	Find all cars that have a SafetyRating of 5.
df1['SafetyRating'] == 5

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23     True
24    False
25     True
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41     True
42    False
43    False
44     True
45    False
46     True
47    False
48    False
49    False
Name: SafetyRating, dtype: bool

In [ ]:
#Grouping and Aggregation Questions
#19.	Find the average Price of cars per brand.
df1.groupby('Brand')['Price'].mean()

Brand
BMW         46216.333333
Ford        50089.181818
Honda       42085.181818
Mercedes    44242.583333
Toyota      43523.900000
Name: Price, dtype: float64

In [ ]:
#20.	Count the number of cars in each FuelType category.
df1.groupby('FuelType')['CarID'].count()

FuelType
Diesel      17
Electric    12
Petrol      21
Name: CarID, dtype: int64

In [ ]:
#21.	Find the highest Price in each Brand.
df1.groupby('Brand')['Price'].max()

Brand
BMW         79402
Ford        77712
Honda       76039
Mercedes    75933
Toyota      71536
Name: Price, dtype: int64

In [ ]:
#22.	Find the lowest Price in each Brand.
df1.groupby('Brand')['Price'].min()

Brand
BMW         24263
Ford        16659
Honda       10300
Mercedes    24117
Toyota      17388
Name: Price, dtype: int64

In [ ]:
#23.	Find the car with the highest ResaleValue.
df1.groupby('ResaleValue')['CarID'].max()

ResaleValue
7139      7
10033     8
11446    46
14128    42
14372    39
14665    13
15836    26
16262    14
17662    27
18884     9
18886    32
18958    37
19006     2
19501    29
19527    24
20293    49
21668    15
22109    48
22622    23
23880     4
24917    30
25545    50
27197    43
27690    16
27816    19
30970     3
31463    31
32004    21
32158    20
32984    10
33468    47
37752    28
40083    38
40647    36
43926    40
45733    25
45789    12
46879    18
48077     5
49844    33
50319    17
50597    45
52467    22
52939    11
53420    44
59039    41
63652    34
66231    35
68106     6
68941     1
Name: CarID, dtype: int64

In [ ]:
#24.	Count the number of cars sold and not sold.
df1.groupby('Sold')['CarID'].count()

Sold
No     25
Yes    25
Name: CarID, dtype: int64

In [ ]:
#25.	Find the average Horsepower per Brand.
df1.groupby('Brand')['Horsepower'].mean()

Brand
BMW         302.666667
Ford        379.636364
Honda       376.363636
Mercedes    289.333333
Toyota      263.400000
Name: Horsepower, dtype: float64

In [ ]:
#26.	Find the highest ResaleValue per Region.
df1.groupby('Region')['Horsepower'].mean()

Region
East     308.272727
North    323.600000
South    300.866667
West     364.142857
Name: Horsepower, dtype: float64

In [ ]:
#27.	Find the lowest Mileage per Brand.
df1.groupby('Brand')['Mileage'].min()

Brand
BMW         13.32
Ford        14.78
Honda       10.61
Mercedes    12.74
Toyota      25.01
Name: Mileage, dtype: float64

In [ ]:
#28.	Count the number of cars per Transmission type.
df1.groupby('Transmission')['CarID'].count()

Transmission
Automatic    22
Manual       28
Name: CarID, dtype: int64

In [ ]:
#Data Manipulation Questions
#29.	Remove the CarID column from the dataset.
df1.head()
df1.drop(columns=['CarID'],inplace=True)

In [ ]:
#30.	Reset the index of the DataFrame.
df1.reset_index(drop=True)

,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
0,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941
1,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006
2,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970
3,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880
4,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077
5,Ford,Explorer,2011,77712,Diesel,41.56,405,341,4,Manual,No,North,2,68106
6,Honda,Pilot,2013,10300,Diesel,17.70,275,332,4,Manual,Yes,South,4,7139
7,Toyota,Prius,2012,17388,Petrol,45.71,378,156,5,Manual,No,South,5,10033
8,Mercedes,GLE,2013,25585,Electric,24.16,326,309,4,Automatic,No,South,1,18884
9,Ford,Explorer,2012,37985,Diesel,37.34,239,473,4,Automatic,No,West,2,32984
10,Ford,Fiesta,2019,67254,Petrol,15.29,134,480,7,Automatic,Yes,South,3,52939
11,Honda,Civic,2020,64608,Electric,10.61,564,332,5,Manual,No,North,5,45789
12,Mercedes,E-Class,2012,29315,Electric,26.83,352,206,7,Manual,Yes,East,1,14665
13,Honda,CR-V,2022,30202,Petrol,39.59,475,312,2,Manual,No,East,1,16262
14,Honda,Civic,2015,34824,Electric,37.11,377,289,4,Manual,Yes,West,3,21668
15,Ford,Focus,2019,43068,Electric,19.92,249,389,5,Manual,Yes,West,3,27690
16,Toyota,Highlander,2020,71536,Petrol,37.93,493,458,7,Manual,No,South,2,50319
17,Ford,Fiesta,2020,63321,Diesel,24.16,407,489,4,Automatic,No,North,1,46879
18,Mercedes,GLC,2013,50248,Diesel,46.46,230,658,2,Manual,No,East,4,27816
19,Honda,Civic,2017,37778,Petrol,24.12,563,163,2,Manual,No,South,2,32158
20,Honda,CR-V,2014,46256,Petrol,16.72,266,255,2,Manual,Yes,East,3,32004
21,Mercedes,GLC,2017,66352,Petrol,43.12,156,516,7,Manual,Yes,East,5,52467
22,Mercedes,C-Class,2021,35241,Electric,33.54,538,342,2,Manual,Yes,East,2,22622
23,Toyota,Camry,2013,28883,Petrol,38.70,213,233,2,Automatic,Yes,South,5,19527
24,Ford,Mustang,2011,62600,Diesel,48.76,496,439,4,Automatic,No,West,4,45733
25,BMW,X3,2010,24263,Electric,13.32,200,415,2,Automatic,Yes,South,5,15836
26,Mercedes,S-Class,2013,27977,Petrol,46.51,300,160,5,Automatic,Yes,West,4,17662
27,Toyota,Corolla,2010,62300,Petrol,34.26,145,454,4,Manual,No,East,3,37752
28,Ford,F-150,2020,30749,Electric,14.78,556,155,2,Manual,No,South,2,19501
29,Toyota,RAV4,2015,36720,Diesel,40.73,147,484,2,Automatic,No,North,1,24917
30,Honda,Fit,2015,38883,Diesel,46.20,565,150,7,Manual,No,West,3,31463
31,Mercedes,C-Class,2012,25800,Petrol,45.72,359,291,5,Automatic,No,South,3,18886
32,Ford,Fiesta,2018,56907,Electric,30.46,506,322,4,Manual,Yes,West,1,49844
33,Mercedes,GLE,2023,75933,Diesel,12.74,244,399,4,Manual,Yes,East,5,63652
34,Ford,Fiesta,2021,77675,Diesel,38.46,118,496,5,Automatic,No,North,4,66231
35,BMW,3 Series,2010,54825,Diesel,20.94,579,491,5,Automatic,No,West,1,40647
36,BMW,X3,2013,29725,Petrol,44.13,235,312,7,Automatic,Yes,South,1,18958
37,Toyota,Prius,2018,64805,Electric,31.16,231,210,5,Automatic,No,South,3,40083
38,Toyota,Camry,2016,20997,Petrol,31.47,107,688,5,Manual,Yes,South,1,14372
39,Toyota,RAV4,2022,68178,Petrol,25.01,134,612,7,Manual,No,West,1,43926
40,Honda,Pilot,2018,76039,Diesel,27.92,498,509,7,Manual,No,North,2,59039
41,Ford,Focus,2020,16659,Petrol,26.08,508,496,4,Manual,No,East,5,14128
42,Honda,Fit,2014,39685,Diesel,49.65,195,266,2,Automatic,Yes,South,2,27197
43,BMW,X5,2023,60310,Petrol,14.98,215,375,2,Automatic,Yes,North,3,53420
44,Mercedes,S-Class,2012,69705,Petrol,16.50,422,586,4,Automatic,Yes,West,5,50597
45,Ford,Explorer,2016,17051,Electric,38.91,558,193,5,Manual,No,West,1,11446
46,Honda,Accord,2015,49903,Diesel,37.78,243,472,5,Automatic,No,North,5,33468
47,Toyota,Highlander,2016,25138,Petrol,49.10,280,202,4,Automatic,No,West,2,22109
48,Toyota,Camry,2014,39294,Petrol,36.95,506,362,5,Manual,Yes,North,1,20293
49,BMW,5 Series,2014,28773,Diesel,44.83,248,252,2,Manual,Yes,South,1,25545

In [ ]:
#31.	Replace all unsold cars ("No") with "Available" in the Sold column.
df1['Sold'] = df1['Sold'].replace('No','Available')

In [ ]:
#32.	Create a new column PerformanceCategory based on Horsepower (High: >300, Medium: 150-300, Low: <150).
df1['PerformanceCategory']=df1['Horsepower'].apply(lambda i:'High' if i > 300 else ('Medium' if i > 150 else 'Low'))

In [ ]:
#33.	Convert the Year column to an integer type.
df1['Year'] = df1['Year'].astype('int')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CarID                50 non-null     int64
 1   Brand                50 non-null     object
 2   Model                50 non-null     object
 3   Year                 50 non-null     int64
 4   Price                50 non-null     int64
 5   FuelType             50 non-null     category
 6   Mileage              50 non-null     float64
 7   Horsepower           50 non-null     int64
 8   Torque               50 non-null     int64
 9   Seats                50 non-null     int64
 10  Transmission         50 non-null     object
 11  Sold                 50 non-null     object
 12  Region               50 non-null     object
 13  SafetyRating         50 non-null     int64
 14  ResaleValue          50 non-null     int64
 15  PerformanceCategory  50 non-null     object
 16  AboveAveragePrice    50 non-null     object
dtypes: category(1), float64(1), int64(8), object(7)
memory usage: 6.6+ KB

In [ ]:
#34.	Create a new column AboveAveragePrice, which is "Yes" if Price is above the average.
avg_price = df1['Price'].mean()
df1['AboveAveragePrice'] = df1['Price'].apply(lambda i:'Yes' if i > avg_price else 'No')

In [ ]:
#35.	Convert the FuelType column to a categorical type.
df1['FuelType'] = df1['FuelType'].astype('category')

In [ ]:
#36.	Find the top 5 most expensive cars.
df1['Price'].sort_values(ascending=False).head(5)

0     79402
5     77712
34    77675
40    76039
33    75933
Name: Price, dtype: int64

In [ ]:
#37.	Find the bottom 5 cheapest cars.
df1['Price'].sort_values(ascending=False).head(5)

0     79402
5     77712
34    77675
40    76039
33    75933
Name: Price, dtype: int64

In [ ]:
df1.head(7)

,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue,PerformanceCategory,AboveAveragePrice
0,1,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941,High,Yes
1,2,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006,Medium,No
2,3,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970,Low,No
3,4,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880,Low,No
4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077,Low,Yes
5,6,Ford,Explorer,2011,77712,Diesel,41.56,405,341,4,Manual,Available,North,2,68106,High,Yes
6,7,Honda,Pilot,2013,10300,Diesel,17.70,275,332,4,Manual,Yes,South,4,7139,Medium,No

In [ ]:
#38.	Save the modified DataFrame to a new CSV file.
df1.to_csv('Modified_Cars_Data')

In [ ]:
#39.	Display the first few rows of the modified DataFrame.
df11 = pd.read_csv("/content/Modified_Cars_Data")
df11.head(5)

,Unnamed: 0,CarID,Brand,Model,Year,Price,FuelType,Mileage,Horsepower,Torque,Seats,Transmission,Sold,Region,SafetyRating,ResaleValue
0,0,1,BMW,5 Series,2022,79402,Diesel,44.91,339,493,2,Manual,Yes,East,1,68941
1,1,2,Mercedes,E-Class,2011,24117,Petrol,15.87,274,289,7,Automatic,Yes,West,4,19006
2,2,3,Mercedes,GLC,2014,40886,Electric,41.57,138,315,2,Automatic,Yes,East,2,30970
3,3,4,Honda,CR-V,2015,34459,Diesel,42.46,119,289,4,Automatic,Yes,West,1,23880
4,4,5,Mercedes,C-Class,2020,59752,Petrol,21.18,133,175,4,Manual,Yes,North,5,48077

In [ ]:
#40.	Count the number of unique car brands in the dataset.
df11['Brand'].count()

np.int64(50)

## ***Questions on Airline Dataset:***

In [ ]:
# 1.	Load the CSV file into a Pandas DataFrame.
df2 = pd.read_csv("/content/drive/MyDrive/Data Sets/airline_passengers_indian.csv")
df2

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold
5,6,Aryan,Nair,22,Male,LH606,Hyderabad,Munich,850,Economy,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
8,9,Saanvi,Joshi,29,Female,UA909,Lucknow,San Francisco,700,Economy,On Hold
9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed
10,11,Advait,Kapoor,32,Male,BA211,Mumbai,London,720,Business,Confirmed
11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
13,14,Kiaan,Jain,31,Male,QR544,Chennai,Dubai,890,Business,On Hold
14,15,Tanish,Agarwal,35,Male,LH633,Kolkata,Tokyo,800,Economy,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [ ]:
#2.	Display the first 5 rows of the DataFrame.
df2.head(5)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold

In [ ]:
#3.	Display the last 5 rows of the DataFrame.
df2.tail(5)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#4.	Get the total number of rows and columns in the DataFrame.
df2.shape

(20, 11)

In [ ]:
#5.	Display all column names in the dataset.
df2.columns

Index(['PassengerID', 'FirstName', 'LastName', 'Age', 'Gender', 'FlightNumber',
       'Departure', 'Destination', 'TicketPrice', 'SeatClass', 'Status'],
      dtype='object')

In [ ]:
#6.	Get summary statistics of numerical columns.
df2.describe()

       PassengerID        Age  TicketPrice
count     20.00000  20.000000    20.000000
mean      10.50000  33.650000   846.000000
std        5.91608   8.034629   218.352684
min        1.00000  22.000000   500.000000
25%        5.75000  27.750000   692.500000
50%       10.50000  32.500000   825.000000
75%       15.25000  38.500000   955.000000
max       20.00000  50.000000  1300.000000

In [ ]:
#7.	Check for missing values in the dataset Data Selection
df2.isnull().sum()

PassengerID     0
FirstName       0
LastName        0
Age             0
Gender          0
FlightNumber    0
Departure       0
Destination     0
TicketPrice     0
SeatClass       0
Status          0
dtype: int64

In [ ]:
#8.	Select only the 'FirstName' and 'LastName' columns.
df2[['FirstName','LastName']]

   FirstName    LastName
0      Aarav      Sharma
1     Vihaan       Verma
2     Vivaan       Patel
3      Anaya       Desai
4       Myra        Iyer
5      Aryan        Nair
6     Ishaan       Mehta
7      Kabir         Rao
8     Saanvi       Joshi
9     Aadhya        Bhat
10    Advait      Kapoor
11     Rudra      Chopra
12      Pari    Malhotra
13     Kiaan        Jain
14    Tanish     Agarwal
15      Riya        Bose
16   Krishna         Das
17   Shaurya      Saxena
18     Tanvi  Chatterjee
19     Arjun       Gupta

In [ ]:
#9.	Retrieve the ticket price of the 10th passenger.
df2.iloc[9]['TicketPrice']

np.int64(650)

In [ ]:
#Filtering & Sorting
#10.	Find all passengers whose ticket price is greater than ₹900.
df2['TicketPrice'] > 900

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7      True
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15     True
16     True
17    False
18    False
19     True
Name: TicketPrice, dtype: bool

In [ ]:
#11.	Count the number of passengers in each seat class.
df2.groupby('SeatClass')['SeatClass'].count()

SeatClass
Business    7
Economy     9
First       4
Name: SeatClass, dtype: int64

In [ ]:
#12.	Find the passenger with the highest ticket price.
df2.head()
df2[df2['TicketPrice'] == df2['TicketPrice'].max()]

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed

In [ ]:
#13.	Get the average ticket price of all passengers.
df2['TicketPrice'].mean()

np.float64(846.0)

In [ ]:
#14.	Sort the passengers by ticket price in descending order.
df2.sort_values(by='TicketPrice',ascending=False)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold
13,14,Kiaan,Jain,31,Male,QR544,Chennai,Dubai,890,Business,On Hold
5,6,Aryan,Nair,22,Male,LH606,Hyderabad,Munich,850,Economy,Confirmed
14,15,Tanish,Agarwal,35,Male,LH633,Kolkata,Tokyo,800,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
10,11,Advait,Kapoor,32,Male,BA211,Mumbai,London,720,Business,Confirmed
8,9,Saanvi,Joshi,29,Female,UA909,Lucknow,San Francisco,700,Economy,On Hold
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed

In [ ]:
#15.	List all passengers who booked a 'First' class ticket.
df2['SeatClass'] == 'First'

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15     True
16    False
17    False
18    False
19    False
Name: SeatClass, dtype: bool

In [ ]:
#Aggregations & Grouping
#20.	Find the average ticket price per seat class.
df2.groupby('SeatClass')['TicketPrice'].mean()

SeatClass
Business     917.142857
Economy      675.555556
First       1105.000000
Name: TicketPrice, dtype: float64

In [ ]:
#21.	Count the number of passengers in each 'AgeGroup'.
df2.groupby('Age').size().sort_values(ascending=False)

Age
22    1
23    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
38    1
40    1
41    1
45    1
48    1
50    1
dtype: int64

In [ ]:
#22.	Find the highest ticket price in each seat class.
df2.groupby('SeatClass')['TicketPrice'].max()

SeatClass
Business    1150
Economy      850
First       1300
Name: TicketPrice, dtype: int64

In [ ]:
#23.	Find the lowest ticket price in each seat class.
df2.head()
df2.groupby('SeatClass')['TicketPrice'].max()

SeatClass
Business    1150
Economy      850
First       1300
Name: TicketPrice, dtype: int64

In [ ]:
#24.	Find the passenger with the highest age.
df2.head()
df2.groupby('PassengerID')['Age'].max()

PassengerID
1     25
2     30
3     45
4     28
5     34
6     22
7     40
8     38
9     29
10    27
11    32
12    26
13    50
14    31
15    35
16    23
17    36
18    41
19    48
20    33
Name: Age, dtype: int64

In [ ]:
(df2['Status'] == 'Confirmed').count()

np.int64(20)

In [ ]:
df2.head()

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold

In [ ]:
#26.	Find the average ticket price of passengers in Business Class.
df2.head()
(df2['SeatClass'] == 'Business').mean()

np.float64(0.35)

In [ ]:
#27.	Find the highest ticket price for each flight.
df2.head()
df2.groupby('FlightNumber')['TicketPrice'].max()

FlightNumber
AF707     950
AF722     970
AI101     500
AI110     650
AI123     670
BA202     750
BA211     720
DL303     600
DL322     580
EK404    1200
EK433    1300
LH606     850
LH633     800
QR505     900
QR544     890
QR567     910
SQ808    1100
SQ833    1150
UA909     700
UA944     730
Name: TicketPrice, dtype: int64

In [ ]:
#Data Transformations
#28.	Remove the 'Gender' column from the dataset.
df2.drop(columns=['Gender'],inplace=True)

In [ ]:
#29.	Reset the index of the dataset.
df2.reset_index(drop=True)

,PassengerID,FirstName,LastName,Age,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,QR505,Kolkata,Tokyo,900,Business,On Hold
5,6,Aryan,Nair,22,LH606,Hyderabad,Munich,850,Economy,Confirmed
6,7,Ishaan,Mehta,40,AF707,Pune,Rome,950,First,Cancelled
7,8,Kabir,Rao,38,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
8,9,Saanvi,Joshi,29,UA909,Lucknow,San Francisco,700,Economy,On Hold
9,10,Aadhya,Bhat,27,AI110,Jaipur,Singapore,650,Economy,Confirmed
10,11,Advait,Kapoor,32,BA211,Mumbai,London,720,Business,Confirmed
11,12,Rudra,Chopra,26,DL322,Delhi,New York,580,Economy,Cancelled
12,13,Pari,Malhotra,50,EK433,Bangalore,Los Angeles,1300,First,Confirmed
13,14,Kiaan,Jain,31,QR544,Chennai,Dubai,890,Business,On Hold
14,15,Tanish,Agarwal,35,LH633,Kolkata,Tokyo,800,Economy,Confirmed
15,16,Riya,Bose,23,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,QR567,Jaipur,Singapore,910,Business,On Hold

In [ ]:
#30.	Replace all 'On Hold' statuses with 'Pending'.
df2['Status'].replace('On Hold','Pending')

0     Confirmed
1     Cancelled
2     Confirmed
3     Confirmed
4       Pending
5     Confirmed
6     Cancelled
7     Confirmed
8       Pending
9     Confirmed
10    Confirmed
11    Cancelled
12    Confirmed
13      Pending
14    Confirmed
15    Confirmed
16      Pending
17    Confirmed
18    Confirmed
19      Pending
Name: Status, dtype: object

In [ ]:
#31.	Replace all ticket prices below ₹600 with 'Low Price'.
df2['TicketPrice'].replace(600,'Low Price')

0           500
1           750
2     Low Price
3          1200
4           900
5           850
6           950
7          1100
8           700
9           650
10          720
11          580
12         1300
13          890
14          800
15          970
16         1150
17          730
18          670
19          910
Name: TicketPrice, dtype: object

In [ ]:
#32.	Convert the 'TicketPrice' column to an integer type.
df2['TicketPrice'].astype('int')

0      500
1      750
2      600
3     1200
4      900
5      850
6      950
7     1100
8      700
9      650
10     720
11     580
12    1300
13     890
14     800
15     970
16    1150
17     730
18     670
19     910
Name: TicketPrice, dtype: int64

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerID   20 non-null     int64
 1   FirstName     20 non-null     object
 2   LastName      20 non-null     object
 3   Age           20 non-null     int64
 4   FlightNumber  20 non-null     object
 5   Departure     20 non-null     object
 6   Destination   20 non-null     object
 7   TicketPrice   20 non-null     int64
 8   SeatClass     20 non-null     object
 9   Status        20 non-null     object
dtypes: int64(3), object(7)
memory usage: 1.7+ KB

In [ ]:
#33.	Create a new column 'AboveAverage' with 'Yes' if the ticket price is above the dataset's average.
Avg_Price=df2['TicketPrice'].mean()
df2['AboveAverage'] = df1['Price'].apply(lambda i: 'Yes' if i > Avg_Price else 'No')

In [ ]:
#34.	Convert the 'SeatClass' column to a categorical data type.
df2['SeatClass'] = df2['SeatClass'].astype('category')

In [ ]:
#Top & Bottom Records
#35.	Find the top 5 passengers with the highest ticket price.
df2.sort_values(by='TicketPrice',ascending=False).head(5)

,PassengerID,FirstName,LastName,Age,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,AboveAverage
12,13,Pari,Malhotra,50,EK433,Bangalore,Los Angeles,1300,First,Confirmed,Yes
3,4,Anaya,Desai,28,EK404,Chennai,Dubai,1200,First,Confirmed,Yes
16,17,Krishna,Das,36,SQ833,Pune,Rome,1150,Business,Pending,Yes
7,8,Kabir,Rao,38,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed,Yes
15,16,Riya,Bose,23,AF722,Hyderabad,Munich,970,First,Confirmed,Yes

In [ ]:
#36.	Find the bottom 5 passengers with the lowest ticket price.
df2.sort_values(by='TicketPrice',ascending=False).tail(5)

,PassengerID,FirstName,LastName,Age,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,AboveAverage
18,19,Tanvi,Chatterjee,48,AI123,Lucknow,San Francisco,670,Economy,Confirmed,Yes
9,10,Aadhya,Bhat,27,AI110,Jaipur,Singapore,650,Economy,Confirmed,Yes
2,3,Vivaan,Patel,45,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,Yes
11,12,Rudra,Chopra,26,DL322,Delhi,New York,580,Economy,Cancelled,Yes
0,1,Aarav,Sharma,25,AI101,Mumbai,London,500,Economy,Confirmed,Yes

In [ ]:
#Save Data
#37.	Save the modified DataFrame to a new CSV file.
df2.to_csv('Modified_Airline_Data')

In [ ]:
df2.head(7)

,PassengerID,FirstName,LastName,Age,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,AboveAverage
0,1,Aarav,Sharma,25,AI101,Mumbai,London,500,Economy,Confirmed,Yes
1,2,Vihaan,Verma,30,BA202,Delhi,New York,750,Business,Cancelled,Yes
2,3,Vivaan,Patel,45,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,Yes
3,4,Anaya,Desai,28,EK404,Chennai,Dubai,1200,First,Confirmed,Yes
4,5,Myra,Iyer,34,QR505,Kolkata,Tokyo,900,Business,Pending,Yes
5,6,Aryan,Nair,22,LH606,Hyderabad,Munich,850,Economy,Confirmed,Yes
6,7,Ishaan,Mehta,40,AF707,Pune,Rome,950,First,Cancelled,Yes

## ***Questions on Hotel Database:***

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df3 = pd.read_csv("/content/drive/MyDrive/hotel_data.csv")
df3

,HotelID,HotelName,Location,RoomType,Rating,PricePerNight,BookingStatus,CheckInDate
0,1,Mountain Inn,Miami,NaN,5.0,200.0,Cancelled,03:16.8
1,2,City Lights Hotel,New York,Double,3.0,100.0,Confirmed,03:16.8
2,3,Ocean View,Miami,Double,NaN,100.0,Cancelled,03:16.8
3,4,City Lights Hotel,Los Angeles,Suite,3.0,150.0,Confirmed,03:16.8
4,5,City Lights Hotel,New York,Suite,3.0,NaN,Confirmed,03:16.8
...,...,...,...,...,...,...,...,...
95,96,Ocean View,Chicago,Deluxe,4.0,200.0,Confirmed,03:16.8
96,97,City Lights Hotel,Chicago,Double,4.0,50.0,Cancelled,03:16.8
97,98,Royal Stay,New York,Double,5.0,NaN,Cancelled,03:16.8
98,99,Royal Stay,San Francisco,Double,5.0,250.0,Confirmed,03:16.8
99,100,Grand Palace,Miami,Double,5.0,150.0,Cancelled,03:16.8

In [ ]:
#Data Cleaning Questions
#1.	How do you fill missing values in the Rating column with the value avg(rating) or "Medium"?
avg_rating = df3['Rating'].mean()

df3['Rating'].fillna(avg_rating,inplace=True)

/tmp/ipykernel_972/1904023251.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['Rating'].fillna(avg_rating,inplace=True)

In [ ]:
#2.	Replace missing values in the CustomerName column with "Guest".
df3['CustomerName'].fillna('Guest',inplace=True)
#Shgowing Error Because there is no any column Named "CustomerName"

KeyError: 'CustomerName'

In [ ]:
#3.	Identify and remove any duplicate records from the dataset.
df3.drop_duplicates(inplace=True)

In [ ]:
#4.	Convert the CheckInDate column to a proper datetime format.
df3['CheckInDate']=pd.to_datetime(df3['CheckInDate'])

In [ ]:
#5.	Extract the year from the CheckInDate column.
df3['CheckInYear']=df3['CheckInDate'].dt.year

In [ ]:
#6.	Extract the month from the CheckInDate column.
df3['CheckinMonth']=df3['CheckInDate'].dt.month

In [ ]:
#7.	Extract the day of the week from the CheckInDate column.
df3['CheckinDay']=df3['CheckInDate'].dt.day

In [ ]:
#8.	Find all records where the RoomsAvailable column has values greater than 150.
df3(df3['RoomAvailale'] > 150)
#There is no any column named "RoomsAvailable"

In [ ]:
#9.	Find the hotels that have a price per night greater than 400.
df3['PricePerNight'] > 400

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: PricePerNight, Length: 100, dtype: bool

In [ ]:
#10.Remove hotels that have null values in the Location column.
df3.dropna(subset = ['RoomType'],inplace=True)

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 99
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   HotelID        93 non-null     int64
 1   HotelName      93 non-null     object
 2   Location       93 non-null     object
 3   RoomType       93 non-null     object
 4   Rating         93 non-null     float64
 5   PricePerNight  88 non-null     float64
 6   BookingStatus  82 non-null     object
 7   CheckInDate    93 non-null     datetime64[ns]
 8   CheckInYear    93 non-null     int32
 9   CheckinMonth   93 non-null     int32
 10  CheckinDay     93 non-null     int32
dtypes: datetime64[ns](1), float64(2), int32(3), int64(1), object(4)
memory usage: 7.6+ KB

In [ ]:
#Date-Based Questions
#11.	Find all hotels where the check-in date is in the year 2023.
df3['CheckInDate']=pd.to_datetime(df3['CheckInDate'])
df3[df3['CheckInDate'].dt.year == 2023]

Empty DataFrame
Columns: [HotelID, HotelName, Location, RoomType, Rating, PricePerNight, BookingStatus, CheckInDate, CheckInYear, CheckinMonth, CheckinDay]
Index: []

In [ ]:
#12.	Find hotels where the check-in date falls on a weekend (Saturday or Sunday).
df3[df3['CheckInDate'].dt.dayofweek.isin([5,6])]

,HotelID,HotelName,Location,RoomType,Rating,PricePerNight,BookingStatus,CheckInDate,CheckInYear,CheckinMonth,CheckinDay
1,2,City Lights Hotel,New York,Double,3.000000,100.0,Confirmed,2026-06-20 03:16:48,2026,6,20
2,3,Ocean View,Miami,Double,4.010989,100.0,Cancelled,2026-06-20 03:16:48,2026,6,20
3,4,City Lights Hotel,Los Angeles,Suite,3.000000,150.0,Confirmed,2026-06-20 03:16:48,2026,6,20
4,5,City Lights Hotel,New York,Suite,3.000000,NaN,Confirmed,2026-06-20 03:16:48,2026,6,20
5,6,Royal Stay,San Francisco,Deluxe,4.000000,100.0,Pending,2026-06-20 03:16:48,2026,6,20
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Ocean View,Chicago,Deluxe,4.000000,200.0,Confirmed,2026-06-20 03:16:48,2026,6,20
96,97,City Lights Hotel,Chicago,Double,4.000000,50.0,Cancelled,2026-06-20 03:16:48,2026,6,20
97,98,Royal Stay,New York,Double,5.000000,NaN,Cancelled,2026-06-20 03:16:48,2026,6,20
98,99,Royal Stay,San Francisco,Double,5.000000,250.0,Confirmed,2026-06-20 03:16:48,2026,6,20
99,100,Grand Palace,Miami,Double,5.000000,150.0,Cancelled,2026-06-20 03:16:48,2026,6,20

In [ ]:
#13.	Find the total number of check-ins for each month.
df3.groupby(df3['CheckInDate'].dt.to_period('M')).size().reset_index(name='total_check_ins')

  CheckInDate  total_check_ins
0     2026-06               93

In [ ]:
#14.	Find the number of hotels checked in per city.
df3.groupby('Location')['HotelName'].nunique().reset_index(name='unique_hotels_count')

        Location  unique_hotels_count
0        Chicago                    4
1    Los Angeles                    5
2          Miami                    5
3       New York                    4
4  San Francisco                    5

In [ ]:
#15.	Count the total number of hotels checked in each year.
df3.groupby('CheckInYear')['HotelName'].count().reset_index(name='hotels_count')

   CheckInYear  hotels_count
0         2026            93

In [ ]:
#16.	Find the highest price per night for each location.
df3.groupby('Location')['PricePerNight'].max().reset_index(name='highest_price_per_night')

        Location  highest_price_per_night
0        Chicago                    250.0
1    Los Angeles                    250.0
2          Miami                    250.0
3       New York                    250.0
4  San Francisco                    250.0

In [ ]:
#17.	Find the hotel with the most available rooms.
df3.groupby('RoomType')['HotelName'].nunique().reset_index(name='unique_hotels_count')

  RoomType  unique_hotels_count
0   Deluxe                    5
1   Double                    5
2   Single                    5
3    Suite                    5

In [ ]:
#18.	Find the average rating of hotels per city.
df3.groupby('Location')['Rating'].mean().reset_index(name='Average_Ratings_Per_City')

        Location  Average_Ratings_Per_City
0        Chicago                  4.056777
1    Los Angeles                  3.788069
2          Miami                  3.905808
3       New York                  4.042125
4  San Francisco                  4.250000

In [ ]:
#19.	Find all hotels where the check-in date is in December.
df3[df3['CheckInDate'].dt.month == 12]

Empty DataFrame
Columns: [HotelID, HotelName, Location, RoomType, Rating, PricePerNight, BookingStatus, CheckInDate, CheckInYear, CheckinMonth, CheckinDay]
Index: []

In [ ]:
#20.	Export the cleaned dataset into a new CSV file.
df3.to_csv('cleaned_hotel_data.csv',index=False)

In [ ]:
df3.head(7)

,HotelID,HotelName,Location,RoomType,Rating,PricePerNight,BookingStatus,CheckInDate,CheckInYear,CheckinMonth,CheckinDay
0,1,Mountain Inn,Miami,NaN,5.000000,200.0,Cancelled,2026-06-20 03:16:48,2026,6,20
1,2,City Lights Hotel,New York,Double,3.000000,100.0,Confirmed,2026-06-20 03:16:48,2026,6,20
2,3,Ocean View,Miami,Double,4.010989,100.0,Cancelled,2026-06-20 03:16:48,2026,6,20
3,4,City Lights Hotel,Los Angeles,Suite,3.000000,150.0,Confirmed,2026-06-20 03:16:48,2026,6,20
4,5,City Lights Hotel,New York,Suite,3.000000,NaN,Confirmed,2026-06-20 03:16:48,2026,6,20
5,6,Royal Stay,San Francisco,Deluxe,4.000000,100.0,Pending,2026-06-20 03:16:48,2026,6,20
6,7,Ocean View,Chicago,Deluxe,4.010989,250.0,Cancelled,2026-06-20 03:16:48,2026,6,20

## ***Questions on Hospital Database:***

In [1]:
import numpy as np
import pandas as pd

In [2]:
# SECTION 1: BASIC DATA EXPLORATION (1–15)
#1.	Load the patient master CSV file into a Pandas DataFrame
# Note: Use pd.read_csv() and store it in a DataFrame variable. Make sure the file path is correct.
df1 = pd.read_csv("/content/drive/MyDrive/patient_master_1.csv")
df1

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,169,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,151,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,173,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,167,55,19.7,No,Occasionally,NaN,D105,Star Health,POL129135,2020-03-02
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,157,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

In [3]:
df2 = pd.read_csv("/content/drive/MyDrive/patient_master_2.csv")
df2

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P20001,Sneha,Iyer,Female,44,1981-08-24,AB-,Single,9459863369,user20001@mail.com,...,158,77,30.8,Yes,Occasionally,Asthma,D107,Bajaj Allianz,POL781973,2024-06-23
1,P20002,Sneha,Sharma,Male,44,1981-11-02,AB-,Single,9582805008,user20002@mail.com,...,176,79,25.5,Yes,Occasionally,NaN,D108,ICICI Lombard,POL978070,2020-12-23
2,P20003,Sneha,Joshi,Male,27,1998-08-12,AB+,Single,9386620175,user20003@mail.com,...,177,92,29.4,No,Occasionally,Thyroid,D109,Bajaj Allianz,POL333787,2021-08-27
3,P20004,Suresh,Mehta,Male,59,1966-11-19,O+,Married,9439250392,user20004@mail.com,...,185,81,23.7,Yes,Occasionally,NaN,D107,ICICI Lombard,POL724228,2020-11-19
4,P20005,Amit,Kulkarni,Female,59,1966-01-15,B+,Single,9893075287,user20005@mail.com,...,168,74,26.2,No,No,Hypertension,D114,ICICI Lombard,POL250394,2024-08-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139995,P159996,Arjun,Patil,Female,60,1965-04-21,B+,Married,9630982227,user159996@mail.com,...,184,70,20.7,Yes,No,Thyroid,D102,Reliance General,POL340217,2021-09-02
139996,P159997,Priya,Verma,Female,53,1972-07-09,B+,Married,9309689795,user159997@mail.com,...,171,54,18.5,Yes,No,Cardiac,D103,New India Assurance,POL440488,2021-03-09
139997,P159998,Priya,Gupta,Male,59,1966-11-27,B+,Single,9493413949,user159998@mail.com,...,181,59,18.0,Yes,No,NaN,D100,ICICI Lombard,POL964388,2021-01-20
139998,P159999,Neha,Mehta,Female,27,1998-08-14,A-,Married,9988283820,user159999@mail.com,...,157,82,33.3,No,No,Hypertension,D109,New India Assurance,POL246218,2021-02-07
139999,P160000,Kavita,Sharma,Male,31,1994-09-09,A+,Married,9907216968,user160000@mail.com,...,183,59,17.6,Yes,No,Hypertension,D112,Bajaj Allianz,POL102734,2020-10-01

In [ ]:
#2.	Display the first 5 rows of the dataset
# Note: This helps you quickly understand column names, data format, and sample values.
df1.head()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,169,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,151,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04

In [ ]:
#3.	Display the last 5 rows of the dataset
# Note: Useful to verify the ending records and check data completeness.
df1.tail()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,173,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,167,55,19.7,No,Occasionally,NaN,D105,Star Health,POL129135,2020-03-02
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,157,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

In [ ]:
#4.	Find the total number of rows and columns
# Note: Output should be in the form (rows, columns).
df1.shape

(20000, 25)

In [ ]:
# 5.	Display column names
# Note: Helps identify exact column names to avoid spelling mistakes later.
df1.columns

Index(['Patient_ID', 'First_Name', 'Last_Name', 'Gender', 'Age',
       'Date_of_Birth', 'Blood_Group', 'Marital_Status', 'Phone_Number',
       'Email', 'Address', 'City', 'State', 'Country', 'Pincode', 'Height_cm',
       'Weight_kg', 'BMI', 'Smoking_Status', 'Alcohol_Consumption',
       'Chronic_Condition', 'Primary_Doctor_ID', 'Insurance_Provider',
       'Insurance_Policy_No', 'Registration_Date'],
      dtype='object')

In [ ]:
# 6.	Display data types of all columns
# Note: Verify whether numeric columns are stored as int/float and dates as object/datetime.
df1.dtypes

Patient_ID              object
First_Name              object
Last_Name               object
Gender                  object
Age                      int64
Date_of_Birth           object
Blood_Group             object
Marital_Status          object
Phone_Number             int64
Email                   object
Address                 object
City                    object
State                   object
Country                 object
Pincode                  int64
Height_cm                int64
Weight_kg                int64
BMI                    float64
Smoking_Status          object
Alcohol_Consumption     object
Chronic_Condition       object
Primary_Doctor_ID       object
Insurance_Provider      object
Insurance_Policy_No     object
Registration_Date       object
dtype: object

In [ ]:
# 7.	Show summary statistics for numerical columns
# Note: Includes count, mean, min, max, and standard deviation.
df1.describe()

,Age,Phone_Number,Pincode,Height_cm,Weight_kg,BMI
count,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000
mean,43.882750,9.499262e+09,405528.641150,165.002850,69.975750,25.927300
std,9.481455,2.885452e+08,3206.324183,8.910382,11.827669,5.233785
min,27.000000,9.000107e+09,400001.000000,150.000000,50.000000,15.400000
25%,36.000000,9.251704e+09,402766.500000,157.000000,60.000000,21.800000
50%,44.000000,9.497135e+09,405511.000000,165.000000,70.000000,25.600000
75%,52.000000,9.750070e+09,408298.250000,173.000000,80.000000,29.500000
max,60.000000,9.999997e+09,411099.000000,180.000000,90.000000,40.000000

In [ ]:
# 8.	Show summary statistics for all columns
# Note: Includes categorical stats like unique values and most frequent value.
df1.describe(include='all')

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
count,20000,20000,20000,20000,20000.000000,20000,20000,20000,2.000000e+04,20000,...,20000.000000,20000.000000,20000.000000,20000,20000,15991,20000,20000,20000,20000
unique,20000,10,10,2,NaN,9778,8,2,NaN,20000,...,NaN,NaN,NaN,2,2,4,11,5,19788,1501
top,P19984,Pooja,Patil,Male,NaN,1975-06-07,A+,Single,NaN,user19984@mail.com,...,NaN,NaN,NaN,No,No,Thyroid,D107,New India Assurance,POL144065,2020-04-14
freq,1,2085,2067,10142,NaN,8,2590,10027,NaN,1,...,NaN,NaN,NaN,10036,10041,4014,1857,4077,3,28
mean,NaN,NaN,NaN,NaN,43.882750,NaN,NaN,NaN,9.499262e+09,NaN,...,165.002850,69.975750,25.927300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,9.481455,NaN,NaN,NaN,2.885452e+08,NaN,...,8.910382,11.827669,5.233785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,NaN,9.000107e+09,NaN,...,150.000000,50.000000,15.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,36.000000,NaN,NaN,NaN,9.251704e+09,NaN,...,157.000000,60.000000,21.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,44.000000,NaN,NaN,NaN,9.497135e+09,NaN,...,165.000000,70.000000,25.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,9.750070e+09,NaN,...,173.000000,80.000000,29.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,9.999997e+09,NaN,...,180.000000,90.000000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 9.	Check how many missing values exist per column
# Note: Identify columns that need data cleaning or filling.
df1.isnull().sum()

Patient_ID                0
First_Name                0
Last_Name                 0
Gender                    0
Age                       0
Date_of_Birth             0
Blood_Group               0
Marital_Status            0
Phone_Number              0
Email                     0
Address                   0
City                      0
State                     0
Country                   0
Pincode                   0
Height_cm                 0
Weight_kg                 0
BMI                       0
Smoking_Status            0
Alcohol_Consumption       0
Chronic_Condition      4009
Primary_Doctor_ID         0
Insurance_Provider        0
Insurance_Policy_No       0
Registration_Date         0
dtype: int64

In [ ]:
# 10.	Check if the dataset contains duplicate Patient_IDs
# Note: Patient_ID should be unique; duplicates indicate data quality issues.
df1.duplicated(subset = ['Patient_ID']).sum()

np.int64(0)

In [ ]:
# 11.	Find the total number of unique patients
# Note: Use Patient_ID to verify uniqueness.
df1.Patient_ID.nunique()

20000

In [ ]:
# 12.	Display memory usage of the DataFrame
# Note: Important when working with large healthcare datasets.
df1.memory_usage()

Index                     132
Patient_ID             160000
First_Name             160000
Last_Name              160000
Gender                 160000
Age                    160000
Date_of_Birth          160000
Blood_Group            160000
Marital_Status         160000
Phone_Number           160000
Email                  160000
Address                160000
City                   160000
State                  160000
Country                160000
Pincode                160000
Height_cm              160000
Weight_kg              160000
BMI                    160000
Smoking_Status         160000
Alcohol_Consumption    160000
Chronic_Condition      160000
Primary_Doctor_ID      160000
Insurance_Provider     160000
Insurance_Policy_No    160000
Registration_Date      160000
dtype: int64

In [ ]:
# 13.	Sort patients by Age in descending order
# Note: Oldest patients should appear first.
df1.sort_values(by = 'Age', ascending = False)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
8399,P08400,Sneha,Singh,Female,60,1965-08-07,AB-,Single,9095205309,user8400@mail.com,...,160,63,24.6,No,No,Hypertension,D105,Reliance General,POL587735,2023-12-23
19,P00020,Pooja,Joshi,Female,60,1965-07-26,B+,Single,9602891328,user20@mail.com,...,172,89,30.1,Yes,No,Diabetes,D109,New India Assurance,POL316461,2022-04-16
14971,P14972,Sneha,Sharma,Female,60,1965-04-13,A-,Single,9763313339,user14972@mail.com,...,175,64,20.9,Yes,No,Diabetes,D107,Star Health,POL672409,2022-01-10
1148,P01149,Anjali,Verma,Male,60,1965-04-25,O+,Single,9311576340,user1149@mail.com,...,155,65,27.1,No,Occasionally,Thyroid,D101,HDFC Ergo,POL842795,2021-11-25
1149,P01150,Neha,Gupta,Male,60,1965-04-25,A+,Married,9481744526,user1150@mail.com,...,166,85,30.8,No,No,Diabetes,D100,ICICI Lombard,POL726612,2020-12-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13482,P13483,Anjali,Singh,Female,27,1998-01-11,A+,Single,9282284476,user13483@mail.com,...,161,75,28.9,No,No,Hypertension,D107,Star Health,POL109831,2022-07-13
8050,P08051,Rahul,Patil,Female,27,1998-01-10,B-,Single,9492374105,user8051@mail.com,...,177,54,17.2,No,No,Hypertension,D104,ICICI Lombard,POL788940,2023-09-09
16179,P16180,Anjali,Patil,Male,27,1998-01-18,A+,Married,9690272656,user16180@mail.com,...,162,72,27.4,No,No,Asthma,D110,HDFC Ergo,POL162004,2022-10-04
16191,P16192,Anjali,Gupta,Male,27,1998-01-18,AB-,Single,9619731561,user16192@mail.com,...,159,81,32.0,No,Occasionally,Hypertension,D107,ICICI Lombard,POL203387,2022-05-09
3456,P03457,Vikas,Verma,Female,27,1998-01-16,A+,Married,9443674753,user3457@mail.com,...,174,75,24.8,Yes,Occasionally,NaN,D102,Star Health,POL260251,2021-04-30

In [ ]:
# 14.	Sort patients by Registration_Date in ascending order
# Note: Earliest registered patients should appear first.
df1.sort_values(by = 'Registration_Date', ascending = True)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
17264,P17265,Amit,Iyer,Male,46,1979-12-10,O+,Single,9104218759,user17265@mail.com,...,159,69,27.3,Yes,No,Asthma,D103,New India Assurance,POL346777,2020-01-01
16781,P16782,Amit,Gupta,Male,35,1990-07-15,A-,Married,9030455935,user16782@mail.com,...,175,69,22.5,Yes,Occasionally,Hypertension,D110,Star Health,POL626041,2020-01-01
3817,P03818,Vikas,Kulkarni,Male,37,1988-10-20,O+,Single,9196624830,user3818@mail.com,...,151,72,31.6,No,Occasionally,Asthma,D110,Reliance General,POL680569,2020-01-01
3955,P03956,Rohan,Mehta,Female,44,1981-03-03,AB-,Married,9639101257,user3956@mail.com,...,160,74,28.9,Yes,No,NaN,D100,Star Health,POL182307,2020-01-01
18676,P18677,Rohan,Mehta,Female,34,1991-11-30,B+,Married,9720232207,user18677@mail.com,...,150,73,32.4,Yes,No,Hypertension,D101,ICICI Lombard,POL684598,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9220,P09221,Anjali,Sharma,Male,40,1985-07-24,B+,Married,9565398228,user9221@mail.com,...,158,76,30.4,No,No,Thyroid,D109,ICICI Lombard,POL911220,2024-02-09
934,P00935,Suresh,Gupta,Female,52,1973-01-17,O-,Married,9536300592,user935@mail.com,...,170,87,30.1,No,No,Asthma,D105,Star Health,POL561380,2024-02-09
4328,P04329,Kavita,Mehta,Female,47,1978-07-01,A+,Married,9318381480,user4329@mail.com,...,173,57,19.0,Yes,Occasionally,Diabetes,D100,HDFC Ergo,POL609907,2024-02-09
1431,P01432,Amit,Kulkarni,Female,35,1990-11-21,A-,Married,9783573955,user1432@mail.com,...,168,82,29.1,No,No,Hypertension,D102,HDFC Ergo,POL922008,2024-02-09
11977,P11978,Rahul,Iyer,Male,55,1970-06-03,AB-,Single,9384205947,user11978@mail.com,...,162,83,31.6,Yes,Occasionally,Hypertension,D106,Reliance General,POL100524,2024-02-09

In [ ]:
# 15.	Display random 10 patient records
# Note: Random sampling helps quick data inspection.
df1.sample(10)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
3682,P03683,Rohan,Verma,Male,41,1984-05-11,A+,Married,9302245361,user3683@mail.com,...,179,80,25.0,Yes,No,Asthma,D106,HDFC Ergo,POL105560,2022-10-09
19415,P19416,Vikas,Kulkarni,Male,59,1966-01-27,AB+,Single,9022208687,user19416@mail.com,...,172,57,19.3,No,Occasionally,Diabetes,D105,Star Health,POL606366,2020-04-17
13912,P13913,Amit,Mehta,Female,40,1985-10-13,O-,Married,9763205557,user13913@mail.com,...,166,55,20.0,Yes,Occasionally,Hypertension,D107,New India Assurance,POL777633,2021-01-25
14280,P14281,Anjali,Iyer,Male,59,1966-12-08,O+,Married,9085766124,user14281@mail.com,...,158,69,27.6,No,Occasionally,Diabetes,D110,HDFC Ergo,POL166069,2022-08-04
18968,P18969,Suresh,Patil,Male,58,1967-01-12,O-,Married,9580254759,user18969@mail.com,...,167,65,23.3,Yes,Occasionally,Asthma,D100,ICICI Lombard,POL985517,2021-05-10
3231,P03232,Rahul,Patil,Female,56,1969-02-03,A+,Single,9616405488,user3232@mail.com,...,163,58,21.8,Yes,Occasionally,Thyroid,D104,Star Health,POL861338,2020-06-13
6297,P06298,Vikas,Gupta,Male,43,1982-04-03,A-,Single,9230902262,user6298@mail.com,...,160,51,19.9,Yes,Occasionally,Diabetes,D108,New India Assurance,POL968867,2022-09-06
5728,P05729,Rahul,Verma,Female,28,1997-05-14,A+,Married,9596691432,user5729@mail.com,...,154,74,31.2,No,No,Thyroid,D107,New India Assurance,POL984765,2020-05-27
14582,P14583,Amit,Verma,Male,39,1986-07-29,O+,Single,9602098782,user14583@mail.com,...,150,76,33.8,Yes,No,Asthma,D102,New India Assurance,POL321235,2023-10-30
6811,P06812,Amit,Joshi,Male,51,1974-06-10,B+,Single,9230943286,user6812@mail.com,...,167,85,30.5,No,No,Diabetes,D102,New India Assurance,POL312538,2020-07-16

In [ ]:
# 🔹 SECTION 2: FILTERING & CONDITIONAL SELECTION (16–35)
# 16.	Find all male patients
# 📝 Note: Filter rows where Gender equals "Male".
df1['Gender'] == 'Male'

0         True
1        False
2         True
3         True
4         True
         ...
19995     True
19996    False
19997    False
19998    False
19999    False
Name: Gender, Length: 20000, dtype: bool

In [ ]:
# 17.	Find all female patients above 50 years
# 📝 Note: Apply two conditions: Gender = Female AND Age > 50.
df1[(df1['Gender'] == 'Female') & (df1['Age'] > 50)]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,user8@mail.com,...,173,60,20.0,Yes,Occasionally,Hypertension,D100,HDFC Ergo,POL523880,2022-03-23
10,P00011,Sneha,Verma,Female,51,1974-03-31,O-,Single,9227251578,user11@mail.com,...,180,89,27.5,Yes,No,Hypertension,D104,Reliance General,POL777223,2021-04-24
12,P00013,Vikas,Verma,Female,56,1969-08-17,A-,Single,9895288162,user13@mail.com,...,165,86,31.6,No,No,NaN,D102,Reliance General,POL970598,2022-10-01
19,P00020,Pooja,Joshi,Female,60,1965-07-26,B+,Single,9602891328,user20@mail.com,...,172,89,30.1,Yes,No,Diabetes,D109,New India Assurance,POL316461,2022-04-16
29,P00030,Rahul,Singh,Female,56,1969-11-16,A+,Single,9881807622,user30@mail.com,...,170,54,18.7,Yes,Occasionally,NaN,D107,New India Assurance,POL122084,2022-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19968,P19969,Suresh,Singh,Female,56,1969-09-07,AB-,Married,9880393201,user19969@mail.com,...,170,65,22.5,No,Occasionally,NaN,D102,Star Health,POL690634,2020-03-29
19983,P19984,Rahul,Iyer,Female,54,1971-07-06,A+,Married,9242052517,user19984@mail.com,...,174,55,18.2,Yes,No,Diabetes,D102,New India Assurance,POL778154,2021-12-26
19992,P19993,Rahul,Iyer,Female,58,1967-01-17,AB-,Single,9138504573,user19993@mail.com,...,174,63,20.8,No,No,Diabetes,D104,Star Health,POL871461,2020-12-23
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

In [ ]:
# 18.	Find patients from Pune city
# 📝 Note: Match exact city name in City column.
df1['City'] == 'Pune'

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: City, Length: 20000, dtype: bool

In [ ]:
# 19.	Find patients suffering from Diabetes
# 📝 Note: Use Chronic_Condition column and filter "Diabetes".
df1['Chronic_Condition'] == 'Diabetes'

0        False
1        False
2        False
3         True
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Chronic_Condition, Length: 20000, dtype: bool

In [ ]:
# 20.	Find patients who are smokers
# 📝 Note: Filter Smoking_Status column for "Yes".
df1['Smoking_Status'] == 'Yes'

0         True
1         True
2        False
3        False
4        False
         ...
19995    False
19996     True
19997    False
19998     True
19999     True
Name: Smoking_Status, Length: 20000, dtype: bool

In [ ]:
# 21.	Find patients who consume alcohol occasionally
# 📝 Note: Match Alcohol_Consumption = "Occasionally".
df1['Alcohol_Consumption'] == 'Occasionally'

0         True
1         True
2        False
3        False
4        False
         ...
19995     True
19996     True
19997     True
19998     True
19999     True
Name: Alcohol_Consumption, Length: 20000, dtype: bool

In [ ]:
# 22.	Find patients with BMI greater than 30
# 📝 Note: BMI > 30 is considered obese (high risk).
df2['BMI'] > 30

0          True
1         False
2         False
3         False
4         False
          ...
139995    False
139996    False
139997    False
139998     True
139999    False
Name: BMI, Length: 140000, dtype: bool

In [ ]:
# 23.	Find patients with no chronic condition
# 📝 Note: Chronic_Condition value should be "None".
df1['Chronic_Condition'] == 'None'

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Chronic_Condition, Length: 20000, dtype: bool

In [ ]:
# 24.	Find patients registered after 2023
# 📝 Note: Convert Registration_Date to datetime and compare year > 2023.
df1['Registration_Date']=pd.to_datetime(df1['Registration_Date'])
df1[df1['Registration_Date'].dt.year > 2023]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
18,P00019,Rahul,Iyer,Female,50,1975-05-13,O-,Single,9270700539,user19@mail.com,...,167,85,30.5,No,Occasionally,Thyroid,D109,New India Assurance,POL826506,2024-01-30
46,P00047,Vikas,Joshi,Female,41,1984-03-04,A+,Single,9515459492,user47@mail.com,...,175,82,26.8,No,Occasionally,Asthma,D106,New India Assurance,POL588076,2024-02-08
184,P00185,Rohan,Patil,Male,40,1985-12-04,B-,Single,9640365767,user185@mail.com,...,157,59,23.9,No,No,NaN,D108,Star Health,POL814638,2024-01-12
323,P00324,Rohan,Patil,Female,58,1967-01-23,A+,Single,9472488990,user324@mail.com,...,172,52,17.6,Yes,Occasionally,Diabetes,D103,Reliance General,POL308419,2024-01-24
326,P00327,Anjali,Verma,Female,36,1989-11-14,O-,Single,9141563522,user327@mail.com,...,168,57,20.2,No,No,Hypertension,D108,New India Assurance,POL584138,2024-02-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19825,P19826,Rahul,Patil,Male,58,1967-11-07,B+,Married,9171417356,user19826@mail.com,...,172,79,26.7,Yes,Occasionally,Diabetes,D107,Star Health,POL157654,2024-01-04
19838,P19839,Rahul,Mehta,Male,53,1972-01-25,B+,Single,9714059749,user19839@mail.com,...,172,68,23.0,Yes,No,Hypertension,D109,Star Health,POL976023,2024-01-29
19870,P19871,Pooja,Patil,Male,60,1965-06-04,AB-,Married,9567748514,user19871@mail.com,...,151,90,39.5,No,Occasionally,Thyroid,D105,HDFC Ergo,POL520153,2024-01-31
19924,P19925,Vikas,Sharma,Female,48,1977-05-23,A+,Married,9448392319,user19925@mail.com,...,156,78,32.1,No,Occasionally,Thyroid,D102,ICICI Lombard,POL832456,2024-01-04
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18

In [ ]:
# 25.	Find patients with blood group O+
# 📝 Note: Exact string match "O+".
df1['Blood_Group'] == 'o+'

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Blood_Group, Length: 20000, dtype: bool

In [ ]:
# 26.	Find patients insured under Star Health
# 📝 Note: Filter Insurance_Provider column.
df1['Insurance_Provider'] == 'Star Health'

0        False
1         True
2        False
3        False
4        False
         ...
19995    False
19996    False
19997     True
19998    False
19999    False
Name: Insurance_Provider, Length: 20000, dtype: bool

In [ ]:
df1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 20000 entries, 0 to 19999
Series name: Registration_Date
Non-Null Count  Dtype
--------------  -----
20000 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.4 KB

In [ ]:
# 27.	Find patients whose height is above 175 cm
# 📝 Note: Numeric filtering using Height_cm column.
df1['Height_cm'] == 175

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Height_cm, Length: 20000, dtype: bool

In [ ]:
# 28.	Find patients aged between 30 and 45
# 📝 Note: Age >= 30 AND Age <= 45.
df1[(df1['Age'] >= 30) & (df1['Age'] <= 45)]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,151,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,user7@mail.com,...,176,88,28.4,Yes,No,NaN,D108,Reliance General,POL682287,2020-03-22
8,P00009,Kavita,Mehta,Female,30,1995-03-30,A+,Married,9853397700,user9@mail.com,...,155,68,28.3,Yes,No,Asthma,D103,Star Health,POL233712,2020-10-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,user19990@mail.com,...,178,55,17.4,Yes,Occasionally,Diabetes,D108,Star Health,POL229492,2022-07-08
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,159,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,user19994@mail.com,...,173,62,20.7,No,Occasionally,Diabetes,D109,Reliance General,POL507705,2020-07-05
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,173,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,157,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02

In [ ]:
# 29.	Find patients from Mumbai OR Pune
# 📝 Note: Use OR condition or isin().
df1[(df1['City'] == 'Mumbai') | (df1['City'] == 'Pune')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,user7@mail.com,...,176,88,28.4,Yes,No,NaN,D108,Reliance General,POL682287,2020-03-22
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,user8@mail.com,...,173,60,20.0,Yes,Occasionally,Hypertension,D100,HDFC Ergo,POL523880,2022-03-23
10,P00011,Sneha,Verma,Female,51,1974-03-31,O-,Single,9227251578,user11@mail.com,...,180,89,27.5,Yes,No,Hypertension,D104,Reliance General,POL777223,2021-04-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19987,P19988,Rohan,Joshi,Male,46,1979-05-02,B-,Married,9549739409,user19988@mail.com,...,163,59,22.2,No,No,NaN,D105,HDFC Ergo,POL189197,2023-08-05
19988,P19989,Vikas,Patil,Male,54,1971-07-25,AB-,Married,9087089590,user19989@mail.com,...,157,59,23.9,No,Occasionally,Hypertension,D103,ICICI Lombard,POL272280,2023-10-27
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,user19990@mail.com,...,178,55,17.4,Yes,Occasionally,Diabetes,D108,Star Health,POL229492,2022-07-08
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,159,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,user19994@mail.com,...,173,62,20.7,No,Occasionally,Diabetes,D109,Reliance General,POL507705,2020-07-05

In [ ]:
# 30.	Find patients who are married and diabetic
# 📝 Note: Marital_Status = Married AND Chronic_Condition = Diabetes.
df1[(df1['Marital_Status'] == 'Married') & (df1['Chronic_Condition'] == 'Diabetes')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
13,P00014,Suresh,Mehta,Female,39,1986-05-10,A-,Married,9240144188,user14@mail.com,...,165,76,27.9,Yes,No,Diabetes,D102,Star Health,POL980183,2022-12-17
15,P00016,Pooja,Iyer,Male,41,1984-04-04,AB-,Married,9131640457,user16@mail.com,...,152,86,37.2,Yes,Occasionally,Diabetes,D107,Reliance General,POL773678,2022-10-31
30,P00031,Vikas,Patil,Male,46,1979-10-08,O-,Married,9558075342,user31@mail.com,...,154,51,21.5,No,Occasionally,Diabetes,D109,Star Health,POL496551,2020-02-26
34,P00035,Amit,Nair,Male,46,1979-02-01,O-,Married,9924224974,user35@mail.com,...,174,78,25.8,No,Occasionally,Diabetes,D109,Star Health,POL338388,2023-10-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19953,P19954,Sneha,Iyer,Male,55,1970-10-26,A-,Married,9207604119,user19954@mail.com,...,177,70,22.3,Yes,No,Diabetes,D107,Reliance General,POL230841,2022-06-22
19977,P19978,Rahul,Gupta,Male,43,1982-07-27,AB-,Married,9402505693,user19978@mail.com,...,159,79,31.2,Yes,Occasionally,Diabetes,D104,HDFC Ergo,POL462578,2022-11-21
19983,P19984,Rahul,Iyer,Female,54,1971-07-06,A+,Married,9242052517,user19984@mail.com,...,174,55,18.2,Yes,No,Diabetes,D102,New India Assurance,POL778154,2021-12-26
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,user19990@mail.com,...,178,55,17.4,Yes,Occasionally,Diabetes,D108,Star Health,POL229492,2022-07-08
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,user19994@mail.com,...,173,62,20.7,No,Occasionally,Diabetes,D109,Reliance General,POL507705,2020-07-05

In [ ]:
# 31.	Find patients whose email contains “gmail”
# 📝 Note: Use string methods for partial match.
df1['Email'].str.contains('gmail')

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Email, Length: 20000, dtype: bool

In [ ]:
# 32.	Find patients whose Patient_ID starts with “P1”
# 📝 Note: Prefix-based filtering.
df1['Patient_ID'].str.startswith('P1')

0        False
1        False
2        False
3        False
4        False
         ...
19995     True
19996     True
19997     True
19998     True
19999    False
Name: Patient_ID, Length: 20000, dtype: bool

In [ ]:
# 33.	Find patients with weight above average weight
# 📝 Note: First calculate average weight, then filter.
df1['Weight_kg'] > df1['Weight_kg'].mean()

0        False
1         True
2         True
3        False
4         True
         ...
19995    False
19996    False
19997    False
19998     True
19999     True
Name: Weight_kg, Length: 20000, dtype: bool

In [ ]:
# 34.	Find patients having Asthma or Thyroid
# 📝 Note: OR condition on Chronic_Condition column.
df1[(df1['Chronic_Condition'] == 'Asthma') | (df1['Chronic_Condition'] == 'Thyroid')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,169,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25
8,P00009,Kavita,Mehta,Female,30,1995-03-30,A+,Married,9853397700,user9@mail.com,...,155,68,28.3,Yes,No,Asthma,D103,Star Health,POL233712,2020-10-24
11,P00012,Rahul,Mehta,Female,50,1975-11-26,AB-,Married,9380410557,user12@mail.com,...,170,82,28.4,No,Occasionally,Asthma,D110,Reliance General,POL684731,2022-12-15
14,P00015,Suresh,Gupta,Male,50,1975-10-23,B-,Single,9498079887,user15@mail.com,...,171,75,25.6,No,No,Thyroid,D106,HDFC Ergo,POL258655,2023-10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19978,P19979,Kavita,Gupta,Male,42,1983-09-27,O+,Married,9514834444,user19979@mail.com,...,163,64,24.1,No,Occasionally,Thyroid,D109,Reliance General,POL399622,2020-03-14
19981,P19982,Vikas,Singh,Female,42,1983-10-27,O+,Single,9179699811,user19982@mail.com,...,164,61,22.7,No,No,Thyroid,D107,Reliance General,POL112807,2021-09-22
19990,P19991,Vikas,Joshi,Male,55,1970-05-20,O+,Single,9551275487,user19991@mail.com,...,160,70,27.3,Yes,No,Thyroid,D108,New India Assurance,POL934323,2020-05-26
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,159,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

In [ ]:
# 35.	Find patients whose BMI is below 18.5
# 📝 Note: BMI < 18.5 indicates underweight.

In [ ]:
# SECTION 3: AGGREGATION & GROUPBY (36–55)
# 36.	Find the average age of patients
# 📝 Note: Use mean aggregation on Age column.
df1['Age'].mean()

np.float64(43.88275)

In [ ]:
# 37.	Find average BMI by gender
# 📝 Note: Group by Gender and calculate mean BMI.
df1.groupby('Gender')['BMI'].mean()

Gender
Female    25.939014
Male      25.915914
Name: BMI, dtype: float64

In [ ]:
# 38.	Count number of patients per city
# 📝 Note: Group by City and count rows.
df1.groupby('City').value_counts()

City    Patient_ID  First_Name  Last_Name  Gender  Age  Date_of_Birth  Blood_Group  Marital_Status  Phone_Number  Email               Address        State        Country  Pincode  Height_cm  Weight_kg  BMI   Smoking_Status  Alcohol_Consumption  Chronic_Condition  Primary_Doctor_ID  Insurance_Provider  Insurance_Policy_No  Registration_Date
Mumbai  P00004      Anjali      Patil      Male    47   1978-12-04     A-           Married         9196136323    user4@mail.com      Local Address  Maharashtra  India    402003   162        60         22.9  No              No                   Diabetes           D101               Reliance General    POL912134            2020-05-17           1
        P00021      Neha        Patil      Female  33   1992-01-08     O+           Single          9560697611    user21@mail.com     Local Address  Maharashtra  India    410744   180        62         19.1  No              Occasionally         Thyroid            D102               ICICI Lombard       POL464019            2021-12-16           1
        P00027      Amit        Patil      Male    35   1990-05-07     AB-          Married         9939874149    user27@mail.com     Local Address  Maharashtra  India    404534   178        57         18.0  No              Occasionally         Asthma             D108               Star Health         POL849460            2023-09-01           1
        P00038      Suresh      Nair       Female  39   1986-02-03     O+           Single          9992549306    user38@mail.com     Local Address  Maharashtra  India    409998   150        58         25.8  Yes             Occasionally         Asthma             D101               ICICI Lombard       POL776079            2021-05-08           1
        P00048      Rahul       Singh      Female  29   1996-12-28     O-           Married         9311382542    user48@mail.com     Local Address  Maharashtra  India    404706   153        50         21.4  No              Occasionally         Diabetes           D105               HDFC Ergo           POL230463            2021-04-18           1
                                                                                                                                                                                                                                                                                                                                                        ..
Pune    P19963      Suresh      Verma      Male    45   1980-01-14     AB-          Single          9516003332    user19963@mail.com  Local Address  Maharashtra  India    400593   166        63         22.9  Yes             No                   Thyroid            D110               Star Health         POL779802            2021-07-29           1
        P19967      Kavita      Patil      Female  57   1968-12-21     A-           Single          9771991467    user19967@mail.com  Local Address  Maharashtra  India    402570   173        89         29.7  Yes             No                   Hypertension       D107               Reliance General    POL374313            2022-07-11           1
        P19971      Vikas       Singh      Male    50   1975-08-05     B-           Single          9694795979    user19971@mail.com  Local Address  Maharashtra  India    405130   154        80         33.7  No              Occasionally         Hypertension       D100               Reliance General    POL958429            2022-09-12           1
        P19973      Neha        Kulkarni   Male    54   1971-02-04     B-           Married         9719340286    user19973@mail.com  Local Address  Maharashtra  India    403567   166        53         19.2  No              No                   Hypertension       D110               Reliance General    POL544991            2023-02-27           1
        P19989      Vikas       Patil      Male    54   1971-07-25     AB-          Married         9087089590    user19989@mail.com  Local Address  Maharashtra  India    403816   157        59         23.9  No              Occasionally         Hypertension       D103               ICICI Lombard       POL272280            2023-10-27           1
Name: count, Length: 15991, dtype: int64

In [ ]:
# 39.	Count number of patients per chronic condition
# 📝 Note: Shows disease distribution.
df1.groupby('Chronic_Condition')['Patient_ID'].count()

Chronic_Condition
Asthma          3998
Diabetes        4014
Hypertension    3965
Thyroid         4014
Name: Patient_ID, dtype: int64

In [ ]:
# 40.	Find maximum age per city
# 📝 Note: Group by City and apply max on Age.
df1.groupby('City')['Age'].max()

City
Mumbai         60
Nagpur         60
Nashik         60
Navi Mumbai    60
Pune           60
Name: Age, dtype: int64

In [ ]:
# 41.	Find minimum BMI per gender
# 📝 Note: Identify lowest BMI per gender group.
df1.groupby('Gender')['BMI'].min()

Gender
Female    15.4
Male      15.4
Name: BMI, dtype: float64

In [ ]:
# 42.	Find average height per city
# 📝 Note: City-wise physical comparison.
df1.groupby('City')['Height_cm'].mean()

City
Mumbai         164.782764
Nagpur         165.090549
Nashik         165.035218
Navi Mumbai    165.071191
Pune           165.030007
Name: Height_cm, dtype: float64

In [ ]:
# 43.	Find total patients per insurance provider
# 📝 Note: Count patients under each insurer.
df1.groupby('Insurance_Provider')['Patient_ID'].count()

Insurance_Provider
HDFC Ergo              3942
ICICI Lombard          3969
New India Assurance    4077
Reliance General       3976
Star Health            4036
Name: Patient_ID, dtype: int64

In [ ]:
# 44.	Find city with highest number of patients
# 📝 Note: Sort aggregated counts.
df1.groupby('City')['Patient_ID'].value_counts()

City    Patient_ID
Mumbai  P00002        1
        P00004        1
        P00021        1
        P00027        1
        P00038        1
                     ..
Pune    P19967        1
        P19971        1
        P19973        1
        P19988        1
        P19989        1
Name: count, Length: 20000, dtype: int64

In [ ]:
# 45.	Find average BMI per smoking status
# 📝 Note: Compare smokers vs non-smokers.
df1.groupby('Smoking_Status')['BMI'].mean()

Smoking_Status
No     25.918135
Yes    25.936532
Name: BMI, dtype: float64

In [ ]:
# 46.	Find number of patients per blood group
# 📝 Note: Useful for healthcare planning.
df1.groupby('Blood_Group')['Patient_ID'].count()

Blood_Group
A+     2590
A-     2493
AB+    2565
AB-    2417
B+     2521
B-     2505
O+     2410
O-     2499
Name: Patient_ID, dtype: int64

In [ ]:
# 47.	Find average age per marital status
# 📝 Note: Demographic insight.
df1.groupby('Marital_Status')['Age'].mean()

Marital_Status
Married    43.895618
Single     43.869951
Name: Age, dtype: float64

In [ ]:
# 48.	Find highest BMI per chronic condition
# 📝 Note: Identify extreme risk cases.
df1.groupby('Chronic_Condition')['BMI'].max()

Chronic_Condition
Asthma          40.0
Diabetes        40.0
Hypertension    40.0
Thyroid         40.0
Name: BMI, dtype: float64

In [ ]:
# 49.	Find lowest weight per city
# 📝 Note: Detect outliers.
df1.groupby('City')['Weight_kg'].mean()

City
Mumbai         69.951555
Nagpur         69.882484
Nashik         69.984375
Navi Mumbai    69.998207
Pune           70.060990
Name: Weight_kg, dtype: float64

In [ ]:
# 50.	Count patients registered per year
# 📝 Note: Extract year from Registration_Date.
df1.groupby(df1['Registration_Date'].dt.year)['Patient_ID'].count()

Registration_Date
2020    4944
2021    4811
2022    4837
2023    4838
2024     570
Name: Patient_ID, dtype: int64

In [ ]:
# 51.	Find insurance provider with maximum patients
# 📝 Note: Rank insurance providers.
df1.groupby('Insurance_Provider')['Patient_ID'].count()

Insurance_Provider
HDFC Ergo              3942
ICICI Lombard          3969
New India Assurance    4077
Reliance General       3976
Star Health            4036
Name: Patient_ID, dtype: int64

In [ ]:
# 52.	Find number of patients per doctor
# 📝 Note: Doctor workload analysis.
df1.groupby('Primary_Doctor_ID')['Patient_ID'].count()

Primary_Doctor_ID
D100    1821
D101    1789
D102    1841
D103    1846
D104    1820
D105    1809
D106    1733
D107    1857
D108    1852
D109    1806
D110    1826
Name: Patient_ID, dtype: int64

In [ ]:
# 53.	Find average BMI per doctor
# 📝 Note: Care quality insight.
df1.groupby('Primary_Doctor_ID')['BMI'].mean()

Primary_Doctor_ID
D100    25.969577
D101    25.832700
D102    26.107496
D103    26.128277
D104    25.819615
D105    25.869707
D106    25.856145
D107    25.877975
D108    26.002376
D109    25.864673
D110    25.860843
Name: BMI, dtype: float64

In [ ]:
# 54. find total patients with chronic conditions
# 📝 note: exclude "none".
df1[df1['Chronic_Condition'].notna()].groupby('Chronic_Condition')['Patient_ID'].count()

Chronic_Condition
Asthma          3998
Diabetes        4014
Hypertension    3965
Thyroid         4014
Name: Patient_ID, dtype: int64

In [ ]:
# 55.	Find percentage of smokers vs non-smokers
# 📝 Note: Convert counts into percentages.
df1['Smoking_Status'].value_counts(normalize=True) * 100

Smoking_Status
No     50.18
Yes    49.82
Name: proportion, dtype: float64

In [ ]:
# 🔹 SECTION 4: DATA TRANSFORMATION (56–75)
# 56.	Create a new column Age_Group (Young, Adult, Senior)
# 📝 Note:
# o	Age 5–25 → Young
# o	Age 26–50 → Adult
# o	Age Above 50 → Senior
df1['Age_Group'] = df1['Age'].apply(lambda x: 'Young' if 5 <= x <= 25 else ('Adult' if 26 <= x <= 50 else 'Senior'))

In [ ]:
# 57.	Create a column Risk_Level based on BMI
# 📝 Note:
# o	BMI < 18.5 → Low
# o	BMI 18.5–25 → Normal
# o	BMI 25–30 → Medium
# o	BMI > 30 → High
df1['Risk_Level'] = df1['BMI'].apply(lambda i: 'Low' if i < 18.5 else ('Normal' if 18.5 <= i <= 25 else ('Medium' if 25 < i <= 30 else 'High')))

In [ ]:
# 58.	Convert Registration_Date to datetime
# 📝 Note: Required before extracting year or month.
df1['Registration_Date'] = pd.to_datetime(df1['Registration_Date'])

In [ ]:
# 59.	Extract Registration Year
# 📝 Note: Create a new column storing year only.
df1['Registration_Year']=df1['Registration_Date'].dt.year

In [ ]:
# 60.	Extract Registration Month
# 📝 Note: Month should be numeric (1–12).
df1['Registration_Month']=df1['Registration_Date'].dt.month

In [ ]:
# 61.	Create column Is_Senior (Age > 60)
# 📝 Note: True if Age > 60, else False.
df1['Is_Senior']=df1['Age'].apply(lambda i: 'Yes' if i > 60 else 'No')

In [ ]:
# 62.	Create column High_Risk_Patient
# 📝 Note:
# o	BMI > 30
# o	AND Chronic_Condition ≠ "None"
# Create column with True/False based on conditions
df1['High_Risk_Patient'] = (df1['BMI'] > 30) & (df1['Chronic_Condition'] != 'None')

In [ ]:
# 63.	Convert Gender column to category type
# 📝 Note: Improves memory efficiency.
df1['Gender'] = pd.Categorical(df1['Gender'])

In [ ]:
# 64.	Convert Blood_Group column to category
# 📝 Note: Limited unique values → ideal for category.
df1['Blood_Group'] = pd.Categorical(df1['Gender'])

In [ ]:
# 65.	Rename column Phone_Number to Contact_Number
# 📝 Note: Use rename operation.
df1 = df1.rename(columns = {'Phone_Number' :'Contact_Number'})

In [ ]:
# 66.	Drop Email column
# 📝 Note: Remove unnecessary or sensitive data.
df1.drop('Email',axis=1,inplace=True)

In [ ]:
# 67.	Fill missing Chronic_Condition with “Unknown”
# 📝 Note: Handle missing values.
df1['Chronic_Condition'] = df1['Chronic_Condition'].fillna('Unknown')

In [ ]:
# 68.	Create BMI_Category
# 📝 Note:
# o	<18.5 → Underweight
# o	18.5–25 → Normal
# o	25–30 → Overweight
# o	30 → Obese
df1['BMI_Category'] = df1['BMI'].apply(lambda i: 'Underweight' if i < 18.5 else ('Normal' if 18.5 <= i <= 25 else ('Overweight' if 25 < i <= 30 else 'Obese')))

In [ ]:
# 69.	Normalize Height column
# 📝 Note: Scale values between 0 and 1.
df1['Height_cm'] = (df1['Height_cm'] - df1['Height_cm'].min()) / (df1['Height_cm'].max() - df1['Height_cm'].min())
df1['Height_cm']

0        0.166667
1        0.600000
2        0.633333
3        0.400000
4        0.033333
           ...
19995    0.766667
19996    0.800000
19997    0.566667
19998    0.233333
19999    0.166667
Name: Height_cm, Length: 20000, dtype: float64

In [ ]:
# 70.	Standardize Weight column
# 📝 Note: Mean = 0, Standard Deviation = 1.
# Apply Z-score standardization: (value - mean) / std
df1['Weight_kg'] = (df1['Weight_kg'] - df1['Weight_kg'].mean()) / df1['Weight_kg'].std()
df1['Weight_kg']

0       -1.688900
1        0.340240
2        0.086598
3       -0.843425
4        1.439358
           ...
19995   -0.589782
19996   -0.758877
19997   -1.266162
19998    0.086598
19999    1.608453
Name: Weight_kg, Length: 20000, dtype: float64

In [ ]:
# 71.	Add column Insurance_Status (Yes/No)
# 📝 Note: Yes if Insurance_Provider exists, else No.
df1['Insurance_Status'] = df1['Insurance_Provider'].apply(lambda i: 'Yes' if pd.notna(i) else 'No')

In [ ]:
# 72.	Create column Patient_Location
# 📝 Note: Combine City and State with separator.
df1['Patient_Location'] = df1['City'] + ',' + df1['State']

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           20000 non-null  object
 1   First_Name           20000 non-null  object
 2   Last_Name            20000 non-null  object
 3   Gender               20000 non-null  category
 4   Age                  20000 non-null  int64
 5   Date_of_Birth        20000 non-null  object
 6   Blood_Group          20000 non-null  category
 7   Marital_Status       20000 non-null  object
 8   Contact_Number       20000 non-null  int64
 9   Email                20000 non-null  object
 10  Address              20000 non-null  object
 11  City                 20000 non-null  object
 12  State                20000 non-null  object
 13  Country              20000 non-null  object
 14  Pincode              20000 non-null  int64
 15  Height_cm            20000 non-null  int64
 16  Weight_kg            20000 non-null  int64
 17  BMI                  20000 non-null  float64
 18  Smoking_Status       20000 non-null  object
 19  Alcohol_Consumption  20000 non-null  object
 20  Chronic_Condition    15991 non-null  object
 21  Primary_Doctor_ID    20000 non-null  object
 22  Insurance_Provider   20000 non-null  object
 23  Insurance_Policy_No  20000 non-null  object
 24  Registration_Date    20000 non-null  datetime64[ns]
 25  Age_Group            20000 non-null  object
 26  Risk_Level           20000 non-null  object
 27  Registration_Year    20000 non-null  int32
 28  Registration_Month   20000 non-null  int32
 29  Is_Senior            20000 non-null  object
 30  High_Risk_Patient    20000 non-null  bool
dtypes: bool(1), category(2), datetime64[ns](1), float64(1), int32(2), int64(5), object(19)
memory usage: 4.2+ MB

In [ ]:
# 73.	Sort patients by BMI descending
# 📝 Note: Highest BMI first.
df1.sort_values(by = 'BMI', ascending = False)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Insurance_Status,Patient_Location
17826,P17827,Kavita,Sharma,Female,40,1985-08-05,AB+,Single,9425136045,user17827@mail.com,...,40.0,Yes,Occasionally,Asthma,D108,ICICI Lombard,POL389818,2022-04-13,Yes,"Pune,Maharashtra"
10001,P10002,Anjali,Singh,Female,56,1969-05-19,B+,Single,9248354863,user10002@mail.com,...,40.0,No,Occasionally,Thyroid,D101,Reliance General,POL280028,2020-12-29,Yes,"Nagpur,Maharashtra"
10369,P10370,Pooja,Singh,Male,34,1991-10-01,O-,Single,9637966832,user10370@mail.com,...,40.0,Yes,No,Asthma,D100,New India Assurance,POL514133,2020-10-28,Yes,"Pune,Maharashtra"
7256,P07257,Vikas,Iyer,Male,38,1987-02-22,B+,Married,9754719239,user7257@mail.com,...,40.0,Yes,No,Thyroid,D108,New India Assurance,POL120798,2021-03-15,Yes,"Navi Mumbai,Maharashtra"
1953,P01954,Pooja,Patil,Male,54,1971-07-26,B+,Single,9195154533,user1954@mail.com,...,40.0,Yes,No,Asthma,D100,ICICI Lombard,POL530780,2023-03-24,Yes,"Nashik,Maharashtra"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10472,P10473,Sneha,Gupta,Male,52,1973-05-06,B-,Married,9673132770,user10473@mail.com,...,15.4,No,No,Thyroid,D108,ICICI Lombard,POL832893,2020-05-07,Yes,"Nagpur,Maharashtra"
9592,P09593,Pooja,Verma,Female,34,1991-12-21,AB+,Single,9794493674,user9593@mail.com,...,15.4,Yes,No,Hypertension,D108,Reliance General,POL516205,2020-12-02,Yes,"Nashik,Maharashtra"
19194,P19195,Neha,Mehta,Male,35,1990-11-15,AB-,Single,9640192581,user19195@mail.com,...,15.4,No,Occasionally,Asthma,D108,New India Assurance,POL996034,2022-02-28,Yes,"Mumbai,Maharashtra"
15514,P15515,Rohan,Mehta,Female,47,1978-09-16,AB-,Married,9527769177,user15515@mail.com,...,15.4,Yes,No,NaN,D108,Star Health,POL135947,2020-10-21,Yes,"Pune,Maharashtra"
19909,P19910,Kavita,Nair,Male,50,1975-07-07,O-,Single,9920944881,user19910@mail.com,...,15.4,Yes,No,Thyroid,D104,ICICI Lombard,POL515871,2023-01-30,Yes,"Nashik,Maharashtra"

In [ ]:
# 74.	Reset index after sorting
# 📝 Note: Clean index after rearranging rows.
df1.reset_index(drop=True, inplace=True)

In [ ]:
# 75.	Select top 10 highest BMI patients
# 📝 Note: Used for high-risk analysis.
df1.sort_values(by = 'BMI', ascending = False).head(10)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Insurance_Status,Patient_Location
17826,P17827,Kavita,Sharma,Female,40,1985-08-05,AB+,Single,9425136045,user17827@mail.com,...,40.0,Yes,Occasionally,Asthma,D108,ICICI Lombard,POL389818,2022-04-13,Yes,"Pune,Maharashtra"
10001,P10002,Anjali,Singh,Female,56,1969-05-19,B+,Single,9248354863,user10002@mail.com,...,40.0,No,Occasionally,Thyroid,D101,Reliance General,POL280028,2020-12-29,Yes,"Nagpur,Maharashtra"
10369,P10370,Pooja,Singh,Male,34,1991-10-01,O-,Single,9637966832,user10370@mail.com,...,40.0,Yes,No,Asthma,D100,New India Assurance,POL514133,2020-10-28,Yes,"Pune,Maharashtra"
7256,P07257,Vikas,Iyer,Male,38,1987-02-22,B+,Married,9754719239,user7257@mail.com,...,40.0,Yes,No,Thyroid,D108,New India Assurance,POL120798,2021-03-15,Yes,"Navi Mumbai,Maharashtra"
1953,P01954,Pooja,Patil,Male,54,1971-07-26,B+,Single,9195154533,user1954@mail.com,...,40.0,Yes,No,Asthma,D100,ICICI Lombard,POL530780,2023-03-24,Yes,"Nashik,Maharashtra"
2913,P02914,Rahul,Joshi,Female,55,1970-06-27,O+,Married,9669114317,user2914@mail.com,...,40.0,No,No,NaN,D100,New India Assurance,POL311020,2021-05-04,Yes,"Navi Mumbai,Maharashtra"
14250,P14251,Rohan,Patil,Female,40,1985-06-23,AB-,Single,9713111126,user14251@mail.com,...,40.0,Yes,No,NaN,D107,Star Health,POL448743,2023-10-07,Yes,"Navi Mumbai,Maharashtra"
14268,P14269,Rahul,Singh,Male,35,1990-07-22,A-,Single,9872545141,user14269@mail.com,...,40.0,Yes,No,Thyroid,D104,HDFC Ergo,POL110527,2023-03-05,Yes,"Nagpur,Maharashtra"
5024,P05025,Anjali,Iyer,Female,57,1968-11-13,O-,Single,9737178788,user5025@mail.com,...,40.0,No,No,Asthma,D104,ICICI Lombard,POL350415,2021-05-26,Yes,"Nagpur,Maharashtra"
17251,P17252,Anjali,Joshi,Female,48,1977-10-07,O-,Married,9254411475,user17252@mail.com,...,40.0,Yes,Occasionally,Diabetes,D104,HDFC Ergo,POL716408,2020-05-25,Yes,"Pune,Maharashtra"

In [ ]:
# 🔹 SECTION 5: ADVANCED / ANALYTICAL QUESTIONS (76–90)
# 76.	Find top 5 cities with highest average BMI
# 📝 Note: Group → Mean → Sort → Top 5.
df1.groupby('City')['BMI'].mean().sort_values(ascending=False).head(5)

City
Mumbai         25.984345
Pune           25.945328
Nashik         25.922247
Navi Mumbai    25.911626
Nagpur         25.873850
Name: BMI, dtype: float64

In [ ]:
# 77.	Find bottom 5 cities with lowest average BMI
# 📝 Note: Ascending order.
df1.groupby('City')['BMI'].mean().sort_values(ascending=True).head(5)

City
Nagpur         25.873850
Navi Mumbai    25.911626
Nashik         25.922247
Pune           25.945328
Mumbai         25.984345
Name: BMI, dtype: float64

In [ ]:
# 78.	Find patients at high cardiovascular risk
# 📝 Note:
# o	Age > 50
# o	BMI > 30
# o	Chronic condition present
df1['high_cardiovascular_risk'] = (df1['Age'] > 50) & (df1['BMI'] > 30) & (df1['Chronic_Condition'].notna())
df1[df1['high_cardiovascular_risk']]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Insurance_Status,Patient_Location,high_cardiovascular_risk
19,P00020,Pooja,Joshi,Female,60,1965-07-26,B+,Single,9602891328,user20@mail.com,...,Yes,No,Diabetes,D109,New India Assurance,POL316461,2022-04-16,Yes,"Pune,Maharashtra",True
31,P00032,Rohan,Iyer,Female,59,1966-02-21,A+,Married,9268186109,user32@mail.com,...,Yes,No,Asthma,D109,Star Health,POL687463,2023-12-24,Yes,"Navi Mumbai,Maharashtra",True
99,P00100,Suresh,Iyer,Male,52,1973-10-05,A-,Single,9521456782,user100@mail.com,...,Yes,No,Thyroid,D109,New India Assurance,POL113007,2021-08-10,Yes,"Navi Mumbai,Maharashtra",True
116,P00117,Suresh,Kulkarni,Female,59,1966-06-02,AB+,Married,9873750443,user117@mail.com,...,Yes,Occasionally,Hypertension,D100,New India Assurance,POL346610,2020-05-11,Yes,"Nashik,Maharashtra",True
144,P00145,Neha,Gupta,Male,54,1971-06-04,A-,Married,9895710208,user145@mail.com,...,Yes,No,Asthma,D108,Star Health,POL566971,2020-08-06,Yes,"Navi Mumbai,Maharashtra",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19938,P19939,Amit,Sharma,Male,52,1973-07-21,O-,Married,9868248614,user19939@mail.com,...,No,Occasionally,Diabetes,D106,Star Health,POL180088,2022-09-19,Yes,"Mumbai,Maharashtra",True
19945,P19946,Suresh,Mehta,Female,59,1966-03-31,A+,Single,9969523120,user19946@mail.com,...,No,Occasionally,Thyroid,D108,Star Health,POL729115,2020-03-13,Yes,"Mumbai,Maharashtra",True
19974,P19975,Pooja,Iyer,Male,52,1973-05-29,A+,Married,9162709155,user19975@mail.com,...,No,No,Thyroid,D108,HDFC Ergo,POL189754,2021-06-08,Yes,"Nagpur,Maharashtra",True
19994,P19995,Suresh,Singh,Male,58,1967-01-14,AB+,Married,9142595611,user19995@mail.com,...,Yes,No,Hypertension,D109,HDFC Ergo,POL281542,2021-12-02,Yes,"Navi Mumbai,Maharashtra",True
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18,Yes,"Nagpur,Maharashtra",True

In [ ]:
# 79.	Find doctor handling maximum chronic patients
# 📝 Note: Filter chronic patients, then group by doctor.
chronic_df = df1[df1['Chronic_Condition'] == 'Yes']
top_doctor = chronic_df['Primary_Doctor_ID'].value_counts().max()

In [ ]:
df1.groupby(df1['Chronic_Condition'] == 'Yes')['Primary_Doctor_ID'].value_counts().max()

1857

In [ ]:
# 80.	Find insurance provider covering most senior citizens
# 📝 Note: Senior = Age > 60.
df1.groupby('Insurance_Provider')['Age'].max()

Insurance_Provider
HDFC Ergo              60
ICICI Lombard          60
New India Assurance    60
Reliance General       60
Star Health            60
Name: Age, dtype: int64

In [ ]:
# 81.	Find patients eligible for lifestyle counseling
# 📝 Note: BMI > 25 OR Smoking = Yes OR Alcohol = Occasionally.
df1['lifestyle_counseling'] = (df1['BMI'] > 25) | (df1['Smoking_Status'] == 'Yes') | (df1['Alcohol_Consumption'] == 'Occasionally')

In [ ]:
# 82.	Identify potential ICU-risk patients
# 📝 Note: Age > 65 AND BMI > 30 AND chronic condition present.
df1['ICU-risk_ patients'] = (df1['Age'] > 65) & (df1['BMI'] > 30) & (df1['Chronic_Condition'].notna())

In [ ]:
# 83.	Find correlation between Age and BMI
# 📝 Note: Measures relationship strength.
df1['Age'].corr(df1['BMI'])

np.float64(-0.006068530558057469)

In [ ]:
# 84.	Detect BMI outliers using IQR
# 📝 Note:
# o	Lower bound = Q1 − 1.5×IQR
# o	Upper bound = Q3 + 1.5×IQR
# 1. Calculate Q1 (25th percentile) and Q3 (75th percentile)
q1 = df1['BMI'].quantile(0.25)
q3 = df1['BMI'].quantile(0.75)

# 2. Calculate the Interquartile Range (IQR)
iqr = q3 - q1

# 3. Determine upper and lower bounds
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

# 4. Filter out the outliers
bmi_outliers = df1[(df1['BMI'] < lower_bound) | (df1['BMI'] > upper_bound)]

print(f"Lower Bound: {lower_bound:.2f}, Upper Bound: {upper_bound:.2f}")
print(f"Total outliers detected: {len(bmi_outliers)}")
print(bmi_outliers[['Patient_ID', 'BMI']])

Lower Bound: 10.25, Upper Bound: 41.05
Total outliers detected: 0
Empty DataFrame
Columns: [Patient_ID, BMI]
Index: []

In [ ]:
# 85.	Create pivot table of Gender vs Chronic Condition
# 📝 Note: Rows = Gender, Columns = Chronic_Condition.

In [5]:
# 86.	Create pivot of City vs Smoking_Status
# 📝 Note: Cross-tab city and smoking habits.
city_smoking_total = pd.crosstab(index=df1['City'], columns=df1['Smoking_Status'], normalize=True)
print(city_smoking_total)

Smoking_Status       No      Yes
City
Mumbai          0.09780  0.09830
Nagpur          0.10165  0.10045
Nashik          0.10270  0.09890
Navi Mumbai     0.09755  0.09770
Pune            0.10210  0.10285

In [8]:
# 87.	Calculate rolling average BMI by age
# 📝 Note: Use window size (e.g., 5).
age_means = df1.groupby('Age')['BMI'].mean().reset_index()
age_means['Rolling_Avg_BMI'] = age_means['BMI'].rolling(window=5, min_periods=1).mean()

In [11]:
# 88.	Rank patients by BMI within each city
# 📝 Note: Ranking should reset per city.
df1.groupby('City')['BMI'].rank(method='dense', ascending=False)

0        172.0
1        119.0
2        132.0
3        152.0
4         10.0
         ...
19995    170.0
19996    179.0
19997    183.0
19998     92.0
19999     20.0
Name: BMI, Length: 20000, dtype: float64

In [10]:
df1.head()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,169,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,151,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04

In [13]:
# 89.	Find percentile rank of BMI
# 📝 Note: Shows relative BMI position.
df1['BMI'].rank(pct=True)

0        0.184125
1        0.538275
2        0.452000
3        0.321975
4        0.990525
           ...
19995    0.195950
19996    0.144375
19997    0.123325
19998    0.708675
19999    0.977850
Name: BMI, Length: 20000, dtype: float64

In [14]:
# 90.	Export cleaned DataFrame to CSV
# 📝 Note: Final output after transformations.
df1.to_csv("Cleaned_Hostital_Dataset",index=False)

## ***Questions on Employee Database:***

In [15]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv("/content/drive/MyDrive/employee_data.csv")
df

,First Name,Last Name,Department,Gender,Location,Joining Date,Joining Month,City,Country,Salary,Bonus
0,Cory,Schroeder,Finance,Male,San Francisco,2023-11-16,November,San Francisco,France,99121,8873
1,Jacqueline,Bowen,IT,Female,San Francisco,2023-06-28,June,San Francisco,India,77594,8206
2,Rhonda,Gonzalez,Marketing,Male,Boston,2020-05-13,May,Boston,Australia,85246,3130
3,Bryan,Clark,Sales,Male,Boston,2016-05-24,May,Boston,Japan,71683,11394
4,Mary,Mcdonald,Operations,Other,Houston,2020-02-20,February,Houston,France,134619,12109
...,...,...,...,...,...,...,...,...,...,...,...
145,Janice,Torres,HR,Female,Houston,2021-02-16,February,Houston,Australia,133220,7272
146,Paul,Green,IT,Female,Los Angeles,2017-12-26,December,Los Angeles,USA,53652,14125
147,Teresa,Martin,Finance,Male,Miami,2022-01-10,January,Miami,France,142552,11998
148,Robyn,Peterson,HR,Female,New York,2024-01-06,January,New York,Canada,133852,11154
149,Heather,Hernandez,Marketing,Male,Boston,2020-12-27,December,Boston,UK,59134,13643